<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPI::ODABAClient Member List</h1>This is the complete list of members for <a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a>, including all inherited members.<p><table>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#910d44fec6e751a21722854cf067843d">ActivateGUIMessages</a>()</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#29a225b7f69ccf39a9fdc7e558d0415f">BackupDB</a>(string cpath, string target, int waitsec)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#707abb920b3a8c1c55a315478f7e9ac2">CheckDB</a>(string dictpath, string cpath, CheckOptions *checkopts, string source, int waitsec)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#e2abfc2780ed45fd084950abbfccdf28">Close</a>()</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#676098692dfe4a8ee1bd9ddf0185aa78">Connect</a>(string servername, int hostport, string cachestring)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#2702357dbffadb760a79068cf4226110">DictDisplay</a>(string dbpath, string ppath)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#ff71769a50a6a9df91d2aaca7b926343">Disconnect</a>()</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#c9a97d58d81c5e10846c6ad1dc4a6256">Exist</a>(string cpath)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#7bf5301306a21bc612468a0b257f379b">GetDataSource</a>(int indx0)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#9d5ce5e7fe71d988f21b14b10bde9190">GetHost</a>()</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#4b3b22489fb5ec8ae08af933ce29f7bc">GetPort</a>()</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#c9c00160c3ca3c7a7e4302fcf62bbecc">GetServerVariable</a>(string varname)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#b11f07d0119f695c4b94aa7a4c49a984">Initialize</a>(string inipath, string applicationname, string progpath, ApplicationTypes applicationtype, bool initservices)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#8210c176157484620dfc7317cf3e3e0f">IsConnected</a>()</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#e0fa6fb216b04e2da73d946b6f5e0c47">KillClient</a>(int clientid, int waitsec, bool sendmessage)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#6f7774cd6efcd6b3b6d639c5bdf0ee31">Open</a>(string inipath, string applicationname, string progpath, ApplicationTypes applicationtype)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#e945465cda96efdab6b6b14cd2c33a73">OpenDataSource</a>(string datasourcename, PIACC accopt)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#fe728cf6203f6517af15e1a1f4791ae2">PackDatabase</a>(string cpath, string temppath)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#8484d92d7ae22f0648690c3ab7c8e16a">RestoreDB</a>(string cpath, string source, int waitsec)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#c6889226d99c230ee3b3abd971151ef7">SendClientMessage</a>(int clientid, string mtext, string mtitle, string mtype)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#160daf8ba319e0ccf9536da868308768">SetServerVariable</a>(string varname, string varstring)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#4c6df86135128a2318e915eeb25ce8b7">ShutDown</a>(string closesystem)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#40895c5380f29d5abb352b61f7a65179">StartPause</a>(int waitsec)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#51847fd895b42e299cde7508e40bee08">StatDisplay</a>(string dbpath, string ppath)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#63bb40a9e1fda4bc5abe9d67df9a2b0f">StopPause</a>()</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1ODABAClient.php#657337d6de75b37462deaa61e22db2da">SysInfoDisplay</a>(string dbpath, string ppath)</td><td><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a></td><td><code> [private]</code></td></tr>
</table><? include "layout/foot.inc.php";?>
