<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPI::SessionFactory Member List</h1>This is the complete list of members for <a class="el" href="classOPI_1_1SessionFactory.php">OPI::SessionFactory</a>, including all inherited members.<p><table>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1SessionFactory.php#629c121574dd4e7ca8818442862933f4">CreateProxy</a>(string name)</td><td><a class="el" href="classOPI_1_1SessionFactory.php">OPI::SessionFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1SessionFactory.php#46088a0a1aaae66c6c175c8658b7e892">shutdown</a>()</td><td><a class="el" href="classOPI_1_1SessionFactory.php">OPI::SessionFactory</a></td><td><code> [private]</code></td></tr>
</table><? include "layout/foot.inc.php";?>
