<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<a class="el" href="namespaceOPI.php">OPI</a>::<a class="el" href="classOPI_1_1OperationHandle.php">OperationHandle</a></div>
<h1>OPI::OperationHandle Class Reference</h1><!-- doxytag: class="OPI::OperationHandle" --><a href="classOPI_1_1OperationHandle-members.php">List of all members.</a><h2>Private Member Functions</h2>
<ul>
<li>bool <a class="el" href="classOPI_1_1OperationHandle.php#b07e2b966e540634484966d0b23ce6f9">CheckExpression</a> (DictionaryHandle *dictptr, string expression, <a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *obhandle, string clsnames)
<li>bool <a class="el" href="classOPI_1_1OperationHandle.php#5950be1e5d663cbb944b72b9d0b13e4a">CheckExpressionInClass</a> (DictionaryHandle *dictptr, <a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *resobj, string clsnames, string exprnames, string impnames)
<li>bool <a class="el" href="classOPI_1_1OperationHandle.php#08aa685898792d46459d4defdc6fc567">Execute</a> ()
<li><a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a> * <a class="el" href="classOPI_1_1OperationHandle.php#bf0503f42ed5bbb2cbf112843002eefb">GetResult</a> ()
<li>int <a class="el" href="classOPI_1_1OperationHandle.php#e7c251c9b2a474c210eea06b52a2392c">GetSize</a> ()
<li>bool <a class="el" href="classOPI_1_1OperationHandle.php#515945497dc0c8a5014632585a0ac7ef">IsValid</a> ()
<li>bool <a class="el" href="classOPI_1_1OperationHandle.php#2cfc9052ab03190d80ba3db80fded9c9">Open</a> (<a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a> *prophdlref)
<li>bool <a class="el" href="classOPI_1_1OperationHandle.php#80c70352f30931ae30a45d0b8adc3721">ProvideExpression</a> (DictionaryHandle *pdictionary, <a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *resobj, <a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *obhandle, string expression)
</ul>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="b07e2b966e540634484966d0b23ce6f9"></a><!-- doxytag: member="OPI::OperationHandle::CheckExpression" ref="b07e2b966e540634484966d0b23ce6f9" args="(DictionaryHandle *dictptr, string expression, DBObjectHandle *obhandle, string clsnames)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::OperationHandle::CheckExpression           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">DictionaryHandle *&nbsp;</td>
          <td class="mdname" nowrap> <em>dictptr</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>expression</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>obhandle</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>clsnames</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="5950be1e5d663cbb944b72b9d0b13e4a"></a><!-- doxytag: member="OPI::OperationHandle::CheckExpressionInClass" ref="5950be1e5d663cbb944b72b9d0b13e4a" args="(DictionaryHandle *dictptr, DBObjectHandle *resobj, string clsnames, string exprnames, string impnames)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::OperationHandle::CheckExpressionInClass           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">DictionaryHandle *&nbsp;</td>
          <td class="mdname" nowrap> <em>dictptr</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>resobj</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>clsnames</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>exprnames</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>impnames</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="08aa685898792d46459d4defdc6fc567"></a><!-- doxytag: member="OPI::OperationHandle::Execute" ref="08aa685898792d46459d4defdc6fc567" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::OperationHandle::Execute           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="bf0503f42ed5bbb2cbf112843002eefb"></a><!-- doxytag: member="OPI::OperationHandle::GetResult" ref="bf0503f42ed5bbb2cbf112843002eefb" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a>* OPI::OperationHandle::GetResult           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="e7c251c9b2a474c210eea06b52a2392c"></a><!-- doxytag: member="OPI::OperationHandle::GetSize" ref="e7c251c9b2a474c210eea06b52a2392c" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">int OPI::OperationHandle::GetSize           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="515945497dc0c8a5014632585a0ac7ef"></a><!-- doxytag: member="OPI::OperationHandle::IsValid" ref="515945497dc0c8a5014632585a0ac7ef" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::OperationHandle::IsValid           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="2cfc9052ab03190d80ba3db80fded9c9"></a><!-- doxytag: member="OPI::OperationHandle::Open" ref="2cfc9052ab03190d80ba3db80fded9c9" args="(PropertyHandle *prophdlref)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::OperationHandle::Open           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>prophdlref</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="80c70352f30931ae30a45d0b8adc3721"></a><!-- doxytag: member="OPI::OperationHandle::ProvideExpression" ref="80c70352f30931ae30a45d0b8adc3721" args="(DictionaryHandle *pdictionary, DBObjectHandle *resobj, DBObjectHandle *obhandle, string expression)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::OperationHandle::ProvideExpression           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">DictionaryHandle *&nbsp;</td>
          <td class="mdname" nowrap> <em>pdictionary</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>resobj</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>obhandle</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>expression</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="OPI_8cpp.php">OPI.cpp</a></ul>
<? include "layout/foot.inc.php";?>
