<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<a class="el" href="namespaceOPI.php">OPI</a>::<a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a></div>
<h1>OPI::DBObjectHandle Class Reference</h1><!-- doxytag: class="OPI::DBObjectHandle" --><hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="OPI_8cpp.php">OPI.cpp</a></ul>
<? include "layout/foot.inc.php";?>
