<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPI::DataSourceHandle Member List</h1>This is the complete list of members for <a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a>, including all inherited members.<p><table>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#9df3759f8375d06758082a93be18fe26">BeginTransaction</a>(bool extta)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#be97ac8389038827deb649d1537489ac">Close</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#1f4ae74d7675187f6004242e01bf1d36">CloseDatabase</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#caac60818cc967c200585e8ea3fac1ff">CloseDBObject</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#4ae6f06d3eafc30d59a1627933c8dbac">CloseDictionary</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#4aab750640b793b4d924f49e70f27bfa">CloseProperty</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#4c86c8cfec12266d6f652c1a88b16e6a">CloseResourceDB</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#44874ce524bb7e57c7cc880bc46538c6">CommitTransaction</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#91980ef0e0976dfc0e78c0c95cbd3a44">Connect</a>(ODABAClient *podabaclient)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#6ce9a3b75e9400fe258312c857da8e5f">Disconnect</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#be4872b8a0f32cce15d20924fe540ca2">Open</a>(ODABAClient *podabaclient, PIACC accmod)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#0e08d32c889c5dcc581f28e17628aa21">OpenDatabase</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#67bcd7591ac579c5ffa6e30075817bfe">OpenDBObject</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#934c1cad052bf1c77baa8145ecb01ed3">OpenDictionary</a>(PIACC accopt)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#bcd5d504d6a7718b3160a1cffa886948">Openi02</a>(ODABAClient *podabaclient, string inifile, string datasourcename)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#3bb44bf3343c37da4d1cbb9b68e07743">Openi1</a>(ODABAClient *podabaclient, string datasourcename)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#de1868ef34898e83c61d7c2d52c5a5fd">OpenProperty</a>(string extname)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#87f22380e06e4db141ac98b6ebfb7418">OpenResourceDB</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#88ce92d64b920eef8b9a05aad3ed7f64">RollBack</a>()</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#1cf18944e68a651dd2e604e9b632de00">SetDatabase</a>(DatabaseHandle *dbhandle, string wbasepath)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#aeab7def6748b3b8e781d865af380af7">SetDataSource</a>(DataSourceHandle *dbdefptr)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#fbdd65acbeff5638995db1f27c284adb">SetDBObject</a>(DBObjectHandle *ohandle, string wobjname)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#c9a870f7f350e12388e47aed7d88987a">SetDictionary</a>(DictionaryHandle *dictptr, string wdictpath)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#dab943e9899812dbee1a0c28eb9a9400">SetResourceDB</a>(DatabaseHandle *dbhandle, string wbasepath)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#b9f4f98d9b237b14164aba219e22d826">Setup</a>(string inifile, string datasourcename)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#2a90e028b8046158b8fc043f507e3d4f">SetupVariables</a>(string datasourcename)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1DataSourceHandle.php#c5bebdd3618c21d0b1172b7a96ded3fa">SetVariables</a>(string datasourcename)</td><td><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a></td><td><code> [private]</code></td></tr>
</table><? include "layout/foot.inc.php";?>
