<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPI::Session Member List</h1>This is the complete list of members for <a class="el" href="classOPI_1_1Session.php">OPI::Session</a>, including all inherited members.<p><table>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1Session.php#c4e79635eba961aa43b967940e705f0c">CreateSession</a>()</td><td><a class="el" href="classOPI_1_1Session.php">OPI::Session</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1Session.php#865bfa929564dba4c4d0608094bce427">Destroy</a>()</td><td><a class="el" href="classOPI_1_1Session.php">OPI::Session</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1Session.php#79d3a071099b435365c64d0c3be3cd05">getName</a>()</td><td><a class="el" href="classOPI_1_1Session.php">OPI::Session</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1Session.php#b595d923c598939a0d1689cc68b0a044">TimeOut</a>(int seconds)</td><td><a class="el" href="classOPI_1_1Session.php">OPI::Session</a></td><td><code> [private]</code></td></tr>
</table><? include "layout/foot.inc.php";?>
