<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPI::OPIFactory Member List</h1>This is the complete list of members for <a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a>, including all inherited members.<p><table>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#31abc14be2bbefc6ebd72e72b5b3066e">Destroy</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#62d0d2b83e7cc0782cb5dbf4f9505fc1">GetCheckOptions</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#aa10cc90d5eac5797110de8212ececff">GetDatabaseHandle</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#ad18c527ecbd48f551b7b9662a4f89e5">GetDataSourceHandle</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#a5b86d2fcce2612ecfe1a7987f9d2f18">GetDBObjectHandle</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#d044b4ce6aa243794a9a4b027c50ec63">GetDictionaryHandle</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#f589ad5d1273282e8ae1a6dfa2374a6d">GetODABAClient</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#6061a9ffeda42c0c2e6486de392f6e90">GetOperationHandle</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
  <tr class="memlist"><td><a class="el" href="classOPI_1_1OPIFactory.php#5bbbff584d64fb1ca1cbeb16a1a1d709">GetPropertyHandle</a>()</td><td><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a></td><td><code> [private]</code></td></tr>
</table><? include "layout/foot.inc.php";?>
