<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<a class="el" href="namespaceOPI.php">OPI</a>::<a class="el" href="classOPI_1_1DataSourceHandle.php">DataSourceHandle</a></div>
<h1>OPI::DataSourceHandle Class Reference</h1><!-- doxytag: class="OPI::DataSourceHandle" --><a href="classOPI_1_1DataSourceHandle-members.php">List of all members.</a><h2>Private Member Functions</h2>
<ul>
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#9df3759f8375d06758082a93be18fe26">BeginTransaction</a> (bool extta)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#be97ac8389038827deb649d1537489ac">Close</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#caac60818cc967c200585e8ea3fac1ff">CloseDBObject</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#1f4ae74d7675187f6004242e01bf1d36">CloseDatabase</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#4ae6f06d3eafc30d59a1627933c8dbac">CloseDictionary</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#4aab750640b793b4d924f49e70f27bfa">CloseProperty</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#4c86c8cfec12266d6f652c1a88b16e6a">CloseResourceDB</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#44874ce524bb7e57c7cc880bc46538c6">CommitTransaction</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#91980ef0e0976dfc0e78c0c95cbd3a44">Connect</a> (<a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *podabaclient)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#6ce9a3b75e9400fe258312c857da8e5f">Disconnect</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#be4872b8a0f32cce15d20924fe540ca2">Open</a> (<a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *podabaclient, <a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">PIACC</a> accmod)
<dl class="el"><dd class="mdescRight">Open empty data source.  <a href="#be4872b8a0f32cce15d20924fe540ca2"></a><br></dl><li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#bcd5d504d6a7718b3160a1cffa886948">Openi02</a> (<a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *podabaclient, string inifile, string datasourcename)
<dl class="el"><dd class="mdescRight">Opening datasource based on ini-file section.  <a href="#bcd5d504d6a7718b3160a1cffa886948"></a><br></dl><li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#3bb44bf3343c37da4d1cbb9b68e07743">Openi1</a> (<a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *podabaclient, string datasourcename)
<dl class="el"><dd class="mdescRight">Opening data source from catalogue.  <a href="#3bb44bf3343c37da4d1cbb9b68e07743"></a><br></dl><li><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> * <a class="el" href="classOPI_1_1DataSourceHandle.php#67bcd7591ac579c5ffa6e30075817bfe">OpenDBObject</a> ()
<li><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a> * <a class="el" href="classOPI_1_1DataSourceHandle.php#0e08d32c889c5dcc581f28e17628aa21">OpenDatabase</a> ()
<li>DictionaryHandle * <a class="el" href="classOPI_1_1DataSourceHandle.php#934c1cad052bf1c77baa8145ecb01ed3">OpenDictionary</a> (<a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">PIACC</a> accopt)
<li><a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a> * <a class="el" href="classOPI_1_1DataSourceHandle.php#de1868ef34898e83c61d7c2d52c5a5fd">OpenProperty</a> (string extname)
<li><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a> * <a class="el" href="classOPI_1_1DataSourceHandle.php#87f22380e06e4db141ac98b6ebfb7418">OpenResourceDB</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#88ce92d64b920eef8b9a05aad3ed7f64">RollBack</a> ()
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#fbdd65acbeff5638995db1f27c284adb">SetDBObject</a> (<a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *ohandle, string wobjname)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#aeab7def6748b3b8e781d865af380af7">SetDataSource</a> (<a class="el" href="classOPI_1_1DataSourceHandle.php">DataSourceHandle</a> *dbdefptr)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#1cf18944e68a651dd2e604e9b632de00">SetDatabase</a> (<a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a> *dbhandle, string wbasepath)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#c9a870f7f350e12388e47aed7d88987a">SetDictionary</a> (DictionaryHandle *dictptr, string wdictpath)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#dab943e9899812dbee1a0c28eb9a9400">SetResourceDB</a> (<a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a> *dbhandle, string wbasepath)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#c5bebdd3618c21d0b1172b7a96ded3fa">SetVariables</a> (string datasourcename)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#b9f4f98d9b237b14164aba219e22d826">Setup</a> (string inifile, string datasourcename)
<li>bool <a class="el" href="classOPI_1_1DataSourceHandle.php#2a90e028b8046158b8fc043f507e3d4f">SetupVariables</a> (string datasourcename)
</ul>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="9df3759f8375d06758082a93be18fe26"></a><!-- doxytag: member="OPI::DataSourceHandle::BeginTransaction" ref="9df3759f8375d06758082a93be18fe26" args="(bool extta)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::BeginTransaction           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">bool&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>extta</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="be97ac8389038827deb649d1537489ac"></a><!-- doxytag: member="OPI::DataSourceHandle::Close" ref="be97ac8389038827deb649d1537489ac" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::Close           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="1f4ae74d7675187f6004242e01bf1d36"></a><!-- doxytag: member="OPI::DataSourceHandle::CloseDatabase" ref="1f4ae74d7675187f6004242e01bf1d36" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::CloseDatabase           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="caac60818cc967c200585e8ea3fac1ff"></a><!-- doxytag: member="OPI::DataSourceHandle::CloseDBObject" ref="caac60818cc967c200585e8ea3fac1ff" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::CloseDBObject           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="4ae6f06d3eafc30d59a1627933c8dbac"></a><!-- doxytag: member="OPI::DataSourceHandle::CloseDictionary" ref="4ae6f06d3eafc30d59a1627933c8dbac" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::CloseDictionary           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="4aab750640b793b4d924f49e70f27bfa"></a><!-- doxytag: member="OPI::DataSourceHandle::CloseProperty" ref="4aab750640b793b4d924f49e70f27bfa" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::CloseProperty           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="4c86c8cfec12266d6f652c1a88b16e6a"></a><!-- doxytag: member="OPI::DataSourceHandle::CloseResourceDB" ref="4c86c8cfec12266d6f652c1a88b16e6a" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::CloseResourceDB           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="44874ce524bb7e57c7cc880bc46538c6"></a><!-- doxytag: member="OPI::DataSourceHandle::CommitTransaction" ref="44874ce524bb7e57c7cc880bc46538c6" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::CommitTransaction           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="91980ef0e0976dfc0e78c0c95cbd3a44"></a><!-- doxytag: member="OPI::DataSourceHandle::Connect" ref="91980ef0e0976dfc0e78c0c95cbd3a44" args="(ODABAClient *podabaclient)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::Connect           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>podabaclient</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="6ce9a3b75e9400fe258312c857da8e5f"></a><!-- doxytag: member="OPI::DataSourceHandle::Disconnect" ref="6ce9a3b75e9400fe258312c857da8e5f" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::Disconnect           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="be4872b8a0f32cce15d20924fe540ca2"></a><!-- doxytag: member="OPI::DataSourceHandle::Open" ref="be4872b8a0f32cce15d20924fe540ca2" args="(ODABAClient *podabaclient, PIACC accmod)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::Open           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>podabaclient</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">PIACC</a>&nbsp;</td>
          <td class="mdname" nowrap> <em>accmod</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Open empty data source. 
<p>
A data source can be opened when the application has filled the external specifications for the data source. At least the dict_path should be set in the data source before openeing. The data source should be opened only, when all external resources to be accessed are defined in the data source. When the client is not connected the server specifications (server_name and port_number) shuold be set as well. This is not necessary when running a local application.     </td>
  </tr>
</table>
<a class="anchor" name="0e08d32c889c5dcc581f28e17628aa21"></a><!-- doxytag: member="OPI::DataSourceHandle::OpenDatabase" ref="0e08d32c889c5dcc581f28e17628aa21" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a>* OPI::DataSourceHandle::OpenDatabase           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="67bcd7591ac579c5ffa6e30075817bfe"></a><!-- doxytag: member="OPI::DataSourceHandle::OpenDBObject" ref="67bcd7591ac579c5ffa6e30075817bfe" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a>* OPI::DataSourceHandle::OpenDBObject           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="934c1cad052bf1c77baa8145ecb01ed3"></a><!-- doxytag: member="OPI::DataSourceHandle::OpenDictionary" ref="934c1cad052bf1c77baa8145ecb01ed3" args="(PIACC accopt)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">DictionaryHandle* OPI::DataSourceHandle::OpenDictionary           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">PIACC</a>&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>accopt</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="bcd5d504d6a7718b3160a1cffa886948"></a><!-- doxytag: member="OPI::DataSourceHandle::Openi02" ref="bcd5d504d6a7718b3160a1cffa886948" args="(ODABAClient *podabaclient, string inifile, string datasourcename)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::Openi02           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>podabaclient</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>inifile</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>datasourcename</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Opening datasource based on ini-file section. 
<p>
The function opens the data source based on external resource definitions passsed in the ini-file. The inifile section name containing the resource definitions is passed as datasource_name to the function. The resource definitions in the data source are filled from the corresponding resource definitions in the ini-file.     </td>
  </tr>
</table>
<a class="anchor" name="3bb44bf3343c37da4d1cbb9b68e07743"></a><!-- doxytag: member="OPI::DataSourceHandle::Openi1" ref="3bb44bf3343c37da4d1cbb9b68e07743" args="(ODABAClient *podabaclient, string datasourcename)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::Openi1           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>podabaclient</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>datasourcename</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Opening data source from catalogue. 
<p>
The function opens the data source based on external resource definitions passsed stored in the data source catalogue. In this case the external resource defitions are read from the catalogue where an entry with the passed datasource_name must exist. Using the catalogue feature the catalogue data source must be provided in a catalogue [DATA-CATALOGUE] section of the ini-file (local application) or in a corresponding section of the server. The resource definitions in the data source are filled from the corresponding resource definitions in the catalogue entry before opening the data source.     </td>
  </tr>
</table>
<a class="anchor" name="de1868ef34898e83c61d7c2d52c5a5fd"></a><!-- doxytag: member="OPI::DataSourceHandle::OpenProperty" ref="de1868ef34898e83c61d7c2d52c5a5fd" args="(string extname)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a>* OPI::DataSourceHandle::OpenProperty           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>extname</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="87f22380e06e4db141ac98b6ebfb7418"></a><!-- doxytag: member="OPI::DataSourceHandle::OpenResourceDB" ref="87f22380e06e4db141ac98b6ebfb7418" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a>* OPI::DataSourceHandle::OpenResourceDB           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="88ce92d64b920eef8b9a05aad3ed7f64"></a><!-- doxytag: member="OPI::DataSourceHandle::RollBack" ref="88ce92d64b920eef8b9a05aad3ed7f64" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::RollBack           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="1cf18944e68a651dd2e604e9b632de00"></a><!-- doxytag: member="OPI::DataSourceHandle::SetDatabase" ref="1cf18944e68a651dd2e604e9b632de00" args="(DatabaseHandle *dbhandle, string wbasepath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::SetDatabase           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>dbhandle</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>wbasepath</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="aeab7def6748b3b8e781d865af380af7"></a><!-- doxytag: member="OPI::DataSourceHandle::SetDataSource" ref="aeab7def6748b3b8e781d865af380af7" args="(DataSourceHandle *dbdefptr)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::SetDataSource           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DataSourceHandle.php">DataSourceHandle</a> *&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>dbdefptr</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="fbdd65acbeff5638995db1f27c284adb"></a><!-- doxytag: member="OPI::DataSourceHandle::SetDBObject" ref="fbdd65acbeff5638995db1f27c284adb" args="(DBObjectHandle *ohandle, string wobjname)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::SetDBObject           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>ohandle</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>wobjname</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="c9a870f7f350e12388e47aed7d88987a"></a><!-- doxytag: member="OPI::DataSourceHandle::SetDictionary" ref="c9a870f7f350e12388e47aed7d88987a" args="(DictionaryHandle *dictptr, string wdictpath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::SetDictionary           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">DictionaryHandle *&nbsp;</td>
          <td class="mdname" nowrap> <em>dictptr</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>wdictpath</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="dab943e9899812dbee1a0c28eb9a9400"></a><!-- doxytag: member="OPI::DataSourceHandle::SetResourceDB" ref="dab943e9899812dbee1a0c28eb9a9400" args="(DatabaseHandle *dbhandle, string wbasepath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::SetResourceDB           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>dbhandle</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>wbasepath</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="b9f4f98d9b237b14164aba219e22d826"></a><!-- doxytag: member="OPI::DataSourceHandle::Setup" ref="b9f4f98d9b237b14164aba219e22d826" args="(string inifile, string datasourcename)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::Setup           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>inifile</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>datasourcename</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="2a90e028b8046158b8fc043f507e3d4f"></a><!-- doxytag: member="OPI::DataSourceHandle::SetupVariables" ref="2a90e028b8046158b8fc043f507e3d4f" args="(string datasourcename)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::SetupVariables           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>datasourcename</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="c5bebdd3618c21d0b1172b7a96ded3fa"></a><!-- doxytag: member="OPI::DataSourceHandle::SetVariables" ref="c5bebdd3618c21d0b1172b7a96ded3fa" args="(string datasourcename)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::DataSourceHandle::SetVariables           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>datasourcename</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="OPI_8cpp.php">OPI.cpp</a></ul>
<? include "layout/foot.inc.php";?>
