<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<a class="el" href="namespaceOPI.php">OPI</a>::<a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a></div>
<h1>OPI::ODABAClient Class Reference</h1><!-- doxytag: class="OPI::ODABAClient" --><a href="classOPI_1_1ODABAClient-members.php">List of all members.</a><h2>Private Member Functions</h2>
<ul>
<li>void <a class="el" href="classOPI_1_1ODABAClient.php#910d44fec6e751a21722854cf067843d">ActivateGUIMessages</a> ()
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#29a225b7f69ccf39a9fdc7e558d0415f">BackupDB</a> (string cpath, string target, int waitsec)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#707abb920b3a8c1c55a315478f7e9ac2">CheckDB</a> (string dictpath, string cpath, <a class="el" href="classOPI_1_1CheckOptions.php">CheckOptions</a> *checkopts, string source, int waitsec)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#e2abfc2780ed45fd084950abbfccdf28">Close</a> ()
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#676098692dfe4a8ee1bd9ddf0185aa78">Connect</a> (string servername, int hostport, string cachestring)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#2702357dbffadb760a79068cf4226110">DictDisplay</a> (string dbpath, string ppath)
<li>void <a class="el" href="classOPI_1_1ODABAClient.php#ff71769a50a6a9df91d2aaca7b926343">Disconnect</a> ()
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#c9a97d58d81c5e10846c6ad1dc4a6256">Exist</a> (string cpath)
<li>string <a class="el" href="classOPI_1_1ODABAClient.php#7bf5301306a21bc612468a0b257f379b">GetDataSource</a> (int indx0)
<li>string <a class="el" href="classOPI_1_1ODABAClient.php#9d5ce5e7fe71d988f21b14b10bde9190">GetHost</a> ()
<li>int <a class="el" href="classOPI_1_1ODABAClient.php#4b3b22489fb5ec8ae08af933ce29f7bc">GetPort</a> ()
<li>string <a class="el" href="classOPI_1_1ODABAClient.php#c9c00160c3ca3c7a7e4302fcf62bbecc">GetServerVariable</a> (string varname)
<li>void <a class="el" href="classOPI_1_1ODABAClient.php#b11f07d0119f695c4b94aa7a4c49a984">Initialize</a> (string inipath, string applicationname, string progpath, <a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a52">ApplicationTypes</a> applicationtype, bool initservices)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#8210c176157484620dfc7317cf3e3e0f">IsConnected</a> ()
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#e0fa6fb216b04e2da73d946b6f5e0c47">KillClient</a> (int clientid, int waitsec, bool sendmessage)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#6f7774cd6efcd6b3b6d639c5bdf0ee31">Open</a> (string inipath, string applicationname, string progpath, <a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a52">ApplicationTypes</a> applicationtype)
<li><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> * <a class="el" href="classOPI_1_1ODABAClient.php#e945465cda96efdab6b6b14cd2c33a73">OpenDataSource</a> (string datasourcename, <a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">PIACC</a> accopt)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#fe728cf6203f6517af15e1a1f4791ae2">PackDatabase</a> (string cpath, string temppath)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#8484d92d7ae22f0648690c3ab7c8e16a">RestoreDB</a> (string cpath, string source, int waitsec)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#c6889226d99c230ee3b3abd971151ef7">SendClientMessage</a> (int clientid, string mtext, string mtitle, string mtype)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#160daf8ba319e0ccf9536da868308768">SetServerVariable</a> (string varname, string varstring)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#4c6df86135128a2318e915eeb25ce8b7">ShutDown</a> (string closesystem)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#40895c5380f29d5abb352b61f7a65179">StartPause</a> (int waitsec)
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#51847fd895b42e299cde7508e40bee08">StatDisplay</a> (string dbpath, string ppath)
<li>void <a class="el" href="classOPI_1_1ODABAClient.php#63bb40a9e1fda4bc5abe9d67df9a2b0f">StopPause</a> ()
<li>bool <a class="el" href="classOPI_1_1ODABAClient.php#657337d6de75b37462deaa61e22db2da">SysInfoDisplay</a> (string dbpath, string ppath)
</ul>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="910d44fec6e751a21722854cf067843d"></a><!-- doxytag: member="OPI::ODABAClient::ActivateGUIMessages" ref="910d44fec6e751a21722854cf067843d" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::ODABAClient::ActivateGUIMessages           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="29a225b7f69ccf39a9fdc7e558d0415f"></a><!-- doxytag: member="OPI::ODABAClient::BackupDB" ref="29a225b7f69ccf39a9fdc7e558d0415f" args="(string cpath, string target, int waitsec)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::BackupDB           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>cpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>target</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap> <em>waitsec</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="707abb920b3a8c1c55a315478f7e9ac2"></a><!-- doxytag: member="OPI::ODABAClient::CheckDB" ref="707abb920b3a8c1c55a315478f7e9ac2" args="(string dictpath, string cpath, CheckOptions *checkopts, string source, int waitsec)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::CheckDB           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>dictpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>cpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="classOPI_1_1CheckOptions.php">CheckOptions</a> *&nbsp;</td>
          <td class="mdname" nowrap> <em>checkopts</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>source</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap> <em>waitsec</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="e2abfc2780ed45fd084950abbfccdf28"></a><!-- doxytag: member="OPI::ODABAClient::Close" ref="e2abfc2780ed45fd084950abbfccdf28" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::Close           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="676098692dfe4a8ee1bd9ddf0185aa78"></a><!-- doxytag: member="OPI::ODABAClient::Connect" ref="676098692dfe4a8ee1bd9ddf0185aa78" args="(string servername, int hostport, string cachestring)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::Connect           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>servername</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap> <em>hostport</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>cachestring</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="2702357dbffadb760a79068cf4226110"></a><!-- doxytag: member="OPI::ODABAClient::DictDisplay" ref="2702357dbffadb760a79068cf4226110" args="(string dbpath, string ppath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::DictDisplay           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>dbpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>ppath</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="ff71769a50a6a9df91d2aaca7b926343"></a><!-- doxytag: member="OPI::ODABAClient::Disconnect" ref="ff71769a50a6a9df91d2aaca7b926343" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::ODABAClient::Disconnect           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="c9a97d58d81c5e10846c6ad1dc4a6256"></a><!-- doxytag: member="OPI::ODABAClient::Exist" ref="c9a97d58d81c5e10846c6ad1dc4a6256" args="(string cpath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::Exist           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>cpath</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="7bf5301306a21bc612468a0b257f379b"></a><!-- doxytag: member="OPI::ODABAClient::GetDataSource" ref="7bf5301306a21bc612468a0b257f379b" args="(int indx0)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">string OPI::ODABAClient::GetDataSource           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>indx0</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="9d5ce5e7fe71d988f21b14b10bde9190"></a><!-- doxytag: member="OPI::ODABAClient::GetHost" ref="9d5ce5e7fe71d988f21b14b10bde9190" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">string OPI::ODABAClient::GetHost           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="4b3b22489fb5ec8ae08af933ce29f7bc"></a><!-- doxytag: member="OPI::ODABAClient::GetPort" ref="4b3b22489fb5ec8ae08af933ce29f7bc" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">int OPI::ODABAClient::GetPort           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="c9c00160c3ca3c7a7e4302fcf62bbecc"></a><!-- doxytag: member="OPI::ODABAClient::GetServerVariable" ref="c9c00160c3ca3c7a7e4302fcf62bbecc" args="(string varname)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">string OPI::ODABAClient::GetServerVariable           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>varname</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="b11f07d0119f695c4b94aa7a4c49a984"></a><!-- doxytag: member="OPI::ODABAClient::Initialize" ref="b11f07d0119f695c4b94aa7a4c49a984" args="(string inipath, string applicationname, string progpath, ApplicationTypes applicationtype, bool initservices)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::ODABAClient::Initialize           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>inipath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>applicationname</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>progpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a52">ApplicationTypes</a>&nbsp;</td>
          <td class="mdname" nowrap> <em>applicationtype</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>bool&nbsp;</td>
          <td class="mdname" nowrap> <em>initservices</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="8210c176157484620dfc7317cf3e3e0f"></a><!-- doxytag: member="OPI::ODABAClient::IsConnected" ref="8210c176157484620dfc7317cf3e3e0f" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::IsConnected           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="e0fa6fb216b04e2da73d946b6f5e0c47"></a><!-- doxytag: member="OPI::ODABAClient::KillClient" ref="e0fa6fb216b04e2da73d946b6f5e0c47" args="(int clientid, int waitsec, bool sendmessage)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::KillClient           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname" nowrap> <em>clientid</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap> <em>waitsec</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>bool&nbsp;</td>
          <td class="mdname" nowrap> <em>sendmessage</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="6f7774cd6efcd6b3b6d639c5bdf0ee31"></a><!-- doxytag: member="OPI::ODABAClient::Open" ref="6f7774cd6efcd6b3b6d639c5bdf0ee31" args="(string inipath, string applicationname, string progpath, ApplicationTypes applicationtype)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::Open           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>inipath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>applicationname</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>progpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a52">ApplicationTypes</a>&nbsp;</td>
          <td class="mdname" nowrap> <em>applicationtype</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="e945465cda96efdab6b6b14cd2c33a73"></a><!-- doxytag: member="OPI::ODABAClient::OpenDataSource" ref="e945465cda96efdab6b6b14cd2c33a73" args="(string datasourcename, PIACC accopt)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a>* OPI::ODABAClient::OpenDataSource           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>datasourcename</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap><a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">PIACC</a>&nbsp;</td>
          <td class="mdname" nowrap> <em>accopt</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="fe728cf6203f6517af15e1a1f4791ae2"></a><!-- doxytag: member="OPI::ODABAClient::PackDatabase" ref="fe728cf6203f6517af15e1a1f4791ae2" args="(string cpath, string temppath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::PackDatabase           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>cpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>temppath</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="8484d92d7ae22f0648690c3ab7c8e16a"></a><!-- doxytag: member="OPI::ODABAClient::RestoreDB" ref="8484d92d7ae22f0648690c3ab7c8e16a" args="(string cpath, string source, int waitsec)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::RestoreDB           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>cpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>source</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>int&nbsp;</td>
          <td class="mdname" nowrap> <em>waitsec</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="c6889226d99c230ee3b3abd971151ef7"></a><!-- doxytag: member="OPI::ODABAClient::SendClientMessage" ref="c6889226d99c230ee3b3abd971151ef7" args="(int clientid, string mtext, string mtitle, string mtype)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::SendClientMessage           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname" nowrap> <em>clientid</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>mtext</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>mtitle</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>mtype</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="160daf8ba319e0ccf9536da868308768"></a><!-- doxytag: member="OPI::ODABAClient::SetServerVariable" ref="160daf8ba319e0ccf9536da868308768" args="(string varname, string varstring)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::SetServerVariable           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>varname</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>varstring</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="4c6df86135128a2318e915eeb25ce8b7"></a><!-- doxytag: member="OPI::ODABAClient::ShutDown" ref="4c6df86135128a2318e915eeb25ce8b7" args="(string closesystem)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::ShutDown           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>closesystem</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="40895c5380f29d5abb352b61f7a65179"></a><!-- doxytag: member="OPI::ODABAClient::StartPause" ref="40895c5380f29d5abb352b61f7a65179" args="(int waitsec)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::StartPause           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>waitsec</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="51847fd895b42e299cde7508e40bee08"></a><!-- doxytag: member="OPI::ODABAClient::StatDisplay" ref="51847fd895b42e299cde7508e40bee08" args="(string dbpath, string ppath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::StatDisplay           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>dbpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>ppath</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="63bb40a9e1fda4bc5abe9d67df9a2b0f"></a><!-- doxytag: member="OPI::ODABAClient::StopPause" ref="63bb40a9e1fda4bc5abe9d67df9a2b0f" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::ODABAClient::StopPause           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="657337d6de75b37462deaa61e22db2da"></a><!-- doxytag: member="OPI::ODABAClient::SysInfoDisplay" ref="657337d6de75b37462deaa61e22db2da" args="(string dbpath, string ppath)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">bool OPI::ODABAClient::SysInfoDisplay           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname" nowrap> <em>dbpath</em>, </td>
        </tr>
        <tr>
          <td class="md" nowrap align="right"></td>
          <td class="md"></td>
          <td class="md" nowrap>string&nbsp;</td>
          <td class="mdname" nowrap> <em>ppath</em></td>
        </tr>
        <tr>
          <td class="md"></td>
          <td class="md">)&nbsp;</td>
          <td class="md" colspan="2"><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="OPI_8cpp.php">OPI.cpp</a></ul>
<? include "layout/foot.inc.php";?>
