<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<a class="el" href="namespaceOPI.php">OPI</a>::<a class="el" href="classOPI_1_1SessionFactory.php">SessionFactory</a></div>
<h1>OPI::SessionFactory Class Reference</h1><!-- doxytag: class="OPI::SessionFactory" --><a href="classOPI_1_1SessionFactory-members.php">List of all members.</a><h2>Private Member Functions</h2>
<ul>
<li><a class="el" href="classOPI_1_1Session.php">Session</a> * <a class="el" href="classOPI_1_1SessionFactory.php#629c121574dd4e7ca8818442862933f4">CreateProxy</a> (string name)
<li>void <a class="el" href="classOPI_1_1SessionFactory.php#46088a0a1aaae66c6c175c8658b7e892">shutdown</a> ()
</ul>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="629c121574dd4e7ca8818442862933f4"></a><!-- doxytag: member="OPI::SessionFactory::CreateProxy" ref="629c121574dd4e7ca8818442862933f4" args="(string name)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1Session.php">Session</a>* OPI::SessionFactory::CreateProxy           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">string&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>name</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="46088a0a1aaae66c6c175c8658b7e892"></a><!-- doxytag: member="OPI::SessionFactory::shutdown" ref="46088a0a1aaae66c6c175c8658b7e892" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::SessionFactory::shutdown           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="OPI_8cpp.php">OPI.cpp</a></ul>
<? include "layout/foot.inc.php";?>
