<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<a class="el" href="namespaceOPI.php">OPI</a>::<a class="el" href="classOPI_1_1OPIFactory.php">OPIFactory</a></div>
<h1>OPI::OPIFactory Class Reference</h1><!-- doxytag: class="OPI::OPIFactory" --><a href="classOPI_1_1OPIFactory-members.php">List of all members.</a><h2>Private Member Functions</h2>
<ul>
<li>void <a class="el" href="classOPI_1_1OPIFactory.php#31abc14be2bbefc6ebd72e72b5b3066e">Destroy</a> ()
<li><a class="el" href="classOPI_1_1CheckOptions.php">CheckOptions</a> * <a class="el" href="classOPI_1_1OPIFactory.php#62d0d2b83e7cc0782cb5dbf4f9505fc1">GetCheckOptions</a> ()
<li><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a> * <a class="el" href="classOPI_1_1OPIFactory.php#a5b86d2fcce2612ecfe1a7987f9d2f18">GetDBObjectHandle</a> ()
<li><a class="el" href="classOPI_1_1DataSourceHandle.php">DataSourceHandle</a> * <a class="el" href="classOPI_1_1OPIFactory.php#ad18c527ecbd48f551b7b9662a4f89e5">GetDataSourceHandle</a> ()
<li><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a> * <a class="el" href="classOPI_1_1OPIFactory.php#aa10cc90d5eac5797110de8212ececff">GetDatabaseHandle</a> ()
<li>DictionaryHandle * <a class="el" href="classOPI_1_1OPIFactory.php#d044b4ce6aa243794a9a4b027c50ec63">GetDictionaryHandle</a> ()
<li><a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a> * <a class="el" href="classOPI_1_1OPIFactory.php#f589ad5d1273282e8ae1a6dfa2374a6d">GetODABAClient</a> ()
<li><a class="el" href="classOPI_1_1OperationHandle.php">OperationHandle</a> * <a class="el" href="classOPI_1_1OPIFactory.php#6061a9ffeda42c0c2e6486de392f6e90">GetOperationHandle</a> ()
<li><a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a> * <a class="el" href="classOPI_1_1OPIFactory.php#5bbbff584d64fb1ca1cbeb16a1a1d709">GetPropertyHandle</a> ()
</ul>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="31abc14be2bbefc6ebd72e72b5b3066e"></a><!-- doxytag: member="OPI::OPIFactory::Destroy" ref="31abc14be2bbefc6ebd72e72b5b3066e" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::OPIFactory::Destroy           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="62d0d2b83e7cc0782cb5dbf4f9505fc1"></a><!-- doxytag: member="OPI::OPIFactory::GetCheckOptions" ref="62d0d2b83e7cc0782cb5dbf4f9505fc1" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1CheckOptions.php">CheckOptions</a>* OPI::OPIFactory::GetCheckOptions           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="aa10cc90d5eac5797110de8212ececff"></a><!-- doxytag: member="OPI::OPIFactory::GetDatabaseHandle" ref="aa10cc90d5eac5797110de8212ececff" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a>* OPI::OPIFactory::GetDatabaseHandle           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="ad18c527ecbd48f551b7b9662a4f89e5"></a><!-- doxytag: member="OPI::OPIFactory::GetDataSourceHandle" ref="ad18c527ecbd48f551b7b9662a4f89e5" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DataSourceHandle.php">DataSourceHandle</a>* OPI::OPIFactory::GetDataSourceHandle           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="a5b86d2fcce2612ecfe1a7987f9d2f18"></a><!-- doxytag: member="OPI::OPIFactory::GetDBObjectHandle" ref="a5b86d2fcce2612ecfe1a7987f9d2f18" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a>* OPI::OPIFactory::GetDBObjectHandle           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="d044b4ce6aa243794a9a4b027c50ec63"></a><!-- doxytag: member="OPI::OPIFactory::GetDictionaryHandle" ref="d044b4ce6aa243794a9a4b027c50ec63" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">DictionaryHandle* OPI::OPIFactory::GetDictionaryHandle           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="f589ad5d1273282e8ae1a6dfa2374a6d"></a><!-- doxytag: member="OPI::OPIFactory::GetODABAClient" ref="f589ad5d1273282e8ae1a6dfa2374a6d" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a>* OPI::OPIFactory::GetODABAClient           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="6061a9ffeda42c0c2e6486de392f6e90"></a><!-- doxytag: member="OPI::OPIFactory::GetOperationHandle" ref="6061a9ffeda42c0c2e6486de392f6e90" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1OperationHandle.php">OperationHandle</a>* OPI::OPIFactory::GetOperationHandle           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="5bbbff584d64fb1ca1cbeb16a1a1d709"></a><!-- doxytag: member="OPI::OPIFactory::GetPropertyHandle" ref="5bbbff584d64fb1ca1cbeb16a1a1d709" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a>* OPI::OPIFactory::GetPropertyHandle           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="OPI_8cpp.php">OPI.cpp</a></ul>
<? include "layout/foot.inc.php";?>
