<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="nav">
<a class="el" href="namespaceOPI.php">OPI</a>::<a class="el" href="classOPI_1_1Session.php">Session</a></div>
<h1>OPI::Session Class Reference</h1><!-- doxytag: class="OPI::Session" --><a href="classOPI_1_1Session-members.php">List of all members.</a><h2>Private Member Functions</h2>
<ul>
<li><a class="el" href="classOPI_1_1OPIFactory.php">OPIFactory</a> * <a class="el" href="classOPI_1_1Session.php#c4e79635eba961aa43b967940e705f0c">CreateSession</a> ()
<li>void <a class="el" href="classOPI_1_1Session.php#865bfa929564dba4c4d0608094bce427">Destroy</a> ()
<li>void <a class="el" href="classOPI_1_1Session.php#b595d923c598939a0d1689cc68b0a044">TimeOut</a> (int seconds)
<li>string <a class="el" href="classOPI_1_1Session.php#79d3a071099b435365c64d0c3be3cd05">getName</a> ()
</ul>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="c4e79635eba961aa43b967940e705f0c"></a><!-- doxytag: member="OPI::Session::CreateSession" ref="c4e79635eba961aa43b967940e705f0c" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top"><a class="el" href="classOPI_1_1OPIFactory.php">OPIFactory</a>* OPI::Session::CreateSession           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="865bfa929564dba4c4d0608094bce427"></a><!-- doxytag: member="OPI::Session::Destroy" ref="865bfa929564dba4c4d0608094bce427" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::Session::Destroy           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="79d3a071099b435365c64d0c3be3cd05"></a><!-- doxytag: member="OPI::Session::getName" ref="79d3a071099b435365c64d0c3be3cd05" args="()" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">string OPI::Session::getName           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="mdname1" valign="top" nowrap>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<a class="anchor" name="b595d923c598939a0d1689cc68b0a044"></a><!-- doxytag: member="OPI::Session::TimeOut" ref="b595d923c598939a0d1689cc68b0a044" args="(int seconds)" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">void OPI::Session::TimeOut           </td>
          <td class="md" valign="top">(&nbsp;</td>
          <td class="md" nowrap valign="top">int&nbsp;</td>
          <td class="mdname1" valign="top" nowrap> <em>seconds</em>          </td>
          <td class="md" valign="top">&nbsp;)&nbsp;</td>
          <td class="md" nowrap><code> [private]</code></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
    </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="OPI_8cpp.php">OPI.cpp</a></ul>
<? include "layout/foot.inc.php";?>
