<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="functions.php"><span>All</span></a></li>
    <li id="current"><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions_func.php#index_a"><span>a</span></a></li>
    <li><a href="functions_func_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_func_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_func_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_func_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_func_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_func_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_func_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_func_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_func_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_func_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_func_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_func_0x6e.php#index_n"><span>n</span></a></li>
    <li id="current"><a href="functions_func_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_func_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_func_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_func_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_func_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_func_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_func_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
&nbsp;
<p>
<h3><a class="anchor" name="index_o">- o -</a></h3><ul>
<li>Open()
: <a class="el" href="classOPI_1_1PropertyHandle.php#731a1f888301de95cd294995b731011d">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1OperationHandle.php#2cfc9052ab03190d80ba3db80fded9c9">OPI::OperationHandle</a>, <a class="el" href="classOPI_1_1ODABAClient.php#6f7774cd6efcd6b3b6d639c5bdf0ee31">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DataSourceHandle.php#be4872b8a0f32cce15d20924fe540ca2">OPI::DataSourceHandle</a><li>OpenBigInt()
: <a class="el" href="classOPI_1_1PropertyHandle.php#bd3a029cc8ac98fda331a8286a5de9e2">OPI::PropertyHandle</a><li>OpenBoolean()
: <a class="el" href="classOPI_1_1PropertyHandle.php#87790d42e45aba1a75a5d56c8b98e729">OPI::PropertyHandle</a><li>OpenChild()
: <a class="el" href="classOPI_1_1PropertyHandle.php#618f0c51a40eddffeebb45f00e00c84b">OPI::PropertyHandle</a><li>OpenChildReference()
: <a class="el" href="classOPI_1_1PropertyHandle.php#562b2419205054721e86fc39db8afc82">OPI::PropertyHandle</a><li>OpenCopy()
: <a class="el" href="classOPI_1_1PropertyHandle.php#25dc0d5a5e8b42538671692514e7f189">OPI::PropertyHandle</a><li>OpenDatabase()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#203fa420b5031e57e402709be1ae5d18">OPI::DBObjectHandle</a>, <a class="el" href="classOPI_1_1DataSourceHandle.php#0e08d32c889c5dcc581f28e17628aa21">OPI::DataSourceHandle</a><li>OpenDataSource()
: <a class="el" href="classOPI_1_1ODABAClient.php#e945465cda96efdab6b6b14cd2c33a73">OPI::ODABAClient</a><li>OpenDate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#5095c09ecb738209dedd43b703191cb2">OPI::PropertyHandle</a><li>OpenDBObject()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#67bcd7591ac579c5ffa6e30075817bfe">OPI::DataSourceHandle</a><li>OpenDictionary()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#f2f3a6d997c1349019935c92175445e0">OPI::DatabaseHandle</a>, <a class="el" href="classOPI_1_1DataSourceHandle.php#934c1cad052bf1c77baa8145ecb01ed3">OPI::DataSourceHandle</a><li>OpenExtent()
: <a class="el" href="classOPI_1_1PropertyHandle.php#41caee4b60b191f073d45639e0647d73">OPI::PropertyHandle</a><li>OpenFloat()
: <a class="el" href="classOPI_1_1PropertyHandle.php#24fc9b4268ddb4e1920fc8b673d4c2b2">OPI::PropertyHandle</a><li>OpenHierarchy()
: <a class="el" href="classOPI_1_1PropertyHandle.php#2b074ff538f87007dfc9df66662174e3">OPI::PropertyHandle</a><li>Openi02()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#bcd5d504d6a7718b3160a1cffa886948">OPI::DataSourceHandle</a><li>Openi1()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#3bb44bf3343c37da4d1cbb9b68e07743">OPI::DataSourceHandle</a><li>OpenInteger()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0262b1d78ad5c542ae4ac32f3ca1bb9f">OPI::PropertyHandle</a><li>OpenObject()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#1fbfb1f9e4e06e8a66b5fb871021a8de">OPI::DBObjectHandle</a><li>OpenProperty()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#de1868ef34898e83c61d7c2d52c5a5fd">OPI::DataSourceHandle</a><li>OpenReference()
: <a class="el" href="classOPI_1_1PropertyHandle.php#8d06eb5f4e16ba852acd6b7dc06a8a7a">OPI::PropertyHandle</a><li>OpenResourceDB()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#87f22380e06e4db141ac98b6ebfb7418">OPI::DataSourceHandle</a><li>OpenSizedString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#928e399de55507e5c2b50e8f5661f74a">OPI::PropertyHandle</a><li>OpenString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#b39b88f5e293b795ca1eaf4ad04a7f64">OPI::PropertyHandle</a><li>OpenTime()
: <a class="el" href="classOPI_1_1PropertyHandle.php#e0426ca571ddce95163146ea4a245482">OPI::PropertyHandle</a><li>OpenTimestamp()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d7d60026ee240f1d5ce2587435bf8529">OPI::PropertyHandle</a><li>OpenWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#8dd3c9038295b5e101cbe81af6aee00b">OPI::DBObjectHandle</a><li>OwnsData()
: <a class="el" href="classOPI_1_1PropertyHandle.php#b885642c04a833810cdf61cba5754183">OPI::PropertyHandle</a></ul>
<? include "layout/foot.inc.php";?>
