<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="functions.php"><span>All</span></a></li>
    <li id="current"><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions_func.php#index_a"><span>a</span></a></li>
    <li><a href="functions_func_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_func_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_func_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_func_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_func_0x66.php#index_f"><span>f</span></a></li>
    <li id="current"><a href="functions_func_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_func_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_func_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_func_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_func_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_func_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_func_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_func_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_func_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_func_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_func_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_func_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_func_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_func_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
&nbsp;
<p>
<h3><a class="anchor" name="index_g">- g -</a></h3><ul>
<li>Get()
: <a class="el" href="classOPI_1_1PropertyHandle.php#020f14afc5c582f3503e74271176309f">OPI::PropertyHandle</a><li>GetAccess()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#bb856363df5e2953ed2029fe26b4e076">OPI::DBObjectHandle</a><li>GetActionResult()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9b1dda585c335ab434139626564da8f5">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#bbee64c5c51e565fcd0a4c9a9be11c13">OPI::DBObjectHandle</a><li>GetArea()
: <a class="el" href="classOPI_1_1PropertyHandle.php#6bc9f1ef89bf962a5070198cb26439b6">OPI::PropertyHandle</a><li>GetAtPosition()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9695d331b2c7583a1aa4ef5686ae79d8">OPI::PropertyHandle</a><li>GetAttribute()
: <a class="el" href="classOPI_1_1PropertyHandle.php#c8e870200c9a7dae1d1d3f11bece2539">OPI::PropertyHandle</a><li>GetBaseProperty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#6dbddb1a1784d32efc9be620058008a1">OPI::PropertyHandle</a><li>GetByKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#b4e257229ee357e1b1a610a7c6c1e96f">OPI::PropertyHandle</a><li>GetCheckOptions()
: <a class="el" href="classOPI_1_1OPIFactory.php#62d0d2b83e7cc0782cb5dbf4f9505fc1">OPI::OPIFactory</a><li>GetCollectionID()
: <a class="el" href="classOPI_1_1PropertyHandle.php#12a7c705a41ac5f830891ca82476740c">OPI::PropertyHandle</a><li>GetCollectionProperty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#57515863f0fa2c5d57d62c28cd67b0e7">OPI::PropertyHandle</a><li>GetCount()
: <a class="el" href="classOPI_1_1PropertyHandle.php#c0cd9a9a4ec85bdfc9186be82cfee728">OPI::PropertyHandle</a><li>GetCurrentIndex()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9af181f5e67a916b2b31e02c1a712810">OPI::PropertyHandle</a><li>GetCurrentSize()
: <a class="el" href="classOPI_1_1PropertyHandle.php#10b672877c264d60ee0148892a997f2a">OPI::PropertyHandle</a><li>GetCurrentType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#979a53a8628bb1aa4fd7bfd735047c30">OPI::PropertyHandle</a><li>GetDatabaseHandle()
: <a class="el" href="classOPI_1_1OPIFactory.php#aa10cc90d5eac5797110de8212ececff">OPI::OPIFactory</a><li>GetDatabaseID()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#dfbd0174061c474bc19981c473cd69dc">OPI::DBObjectHandle</a><li>GetDataSource()
: <a class="el" href="classOPI_1_1ODABAClient.php#7bf5301306a21bc612468a0b257f379b">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#2861da57a1a881487717c229874a03fe">OPI::DBObjectHandle</a><li>GetDataSourceHandle()
: <a class="el" href="classOPI_1_1OPIFactory.php#ad18c527ecbd48f551b7b9662a4f89e5">OPI::OPIFactory</a><li>GetDate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#66ef810dc0326d53a200c8e7117cc974">OPI::PropertyHandle</a><li>GetDateTime()
: <a class="el" href="classOPI_1_1PropertyHandle.php#7e6b7684193c5c81fca0823bdb8a1c1b">OPI::PropertyHandle</a><li>GetDay()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a4c376583004b28fc9353c7de8f14fff">OPI::PropertyHandle</a><li>GetDBHandle()
: <a class="el" href="classOPI_1_1PropertyHandle.php#583caff5e2e0a82fa72d95dc5ae78e6c">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#df5e50f6002f9ed3157bebfd924b8f97">OPI::DBObjectHandle</a><li>GetDBObjectHandle()
: <a class="el" href="classOPI_1_1OPIFactory.php#a5b86d2fcce2612ecfe1a7987f9d2f18">OPI::OPIFactory</a><li>GetDictionary()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1ed0507e5d37dcce015f0887459c13bf">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#405bac24994697f92462408581abcdbc">OPI::DBObjectHandle</a><li>GetDictionaryHandle()
: <a class="el" href="classOPI_1_1OPIFactory.php#d044b4ce6aa243794a9a4b027c50ec63">OPI::OPIFactory</a><li>GetDimension()
: <a class="el" href="classOPI_1_1PropertyHandle.php#eb8fd423ed22a9819f359f2c9afdb8a9">OPI::PropertyHandle</a><li>GetDouble()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ba1f861069a72369c2c66078540b6a78">OPI::PropertyHandle</a><li>GetExtent()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#517fee616ac9e25dd137f62e32427109">OPI::DBObjectHandle</a><li>GetExtentName()
: <a class="el" href="classOPI_1_1PropertyHandle.php#bd288e8bcb9013e2e8f02a7f3e33cef7">OPI::PropertyHandle</a><li>GetExtInstModCount()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0ad093672da8627ce6b9809ccee85cd4">OPI::PropertyHandle</a><li>GetGenAttrType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#03ad7553342590469ac0bc0b25a7545f">OPI::PropertyHandle</a><li>GetGenOrderType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#5e8212a3317c7b4fbd4beabccf6c86fd">OPI::PropertyHandle</a><li>GetGlobalID()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ccecaa6ee7bc1332086a089fda8b9217">OPI::PropertyHandle</a><li>GetGUID()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0756f09e302aaebc01c331b26a72ab4b">OPI::PropertyHandle</a><li>GetHighObject()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#d5de36fca8466b9c1eecea57fa4763a3">OPI::DBObjectHandle</a><li>GetHost()
: <a class="el" href="classOPI_1_1ODABAClient.php#9d5ce5e7fe71d988f21b14b10bde9190">OPI::ODABAClient</a><li>GetHours()
: <a class="el" href="classOPI_1_1PropertyHandle.php#4f5ee30a2b5ac7ada7d088819966274e">OPI::PropertyHandle</a><li>GetID()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ff2222df2b2e4c66a659628f7a49fb26">OPI::PropertyHandle</a><li>GetIdentity()
: <a class="el" href="classOPI_1_1PropertyHandle.php#b31d93d86bd699ae6f8533f50dbb7b01">OPI::PropertyHandle</a><li>GetIndexName()
: <a class="el" href="classOPI_1_1PropertyHandle.php#43338b18628e2b640ef0b543ff3e2f9d">OPI::PropertyHandle</a><li>GetInitInstance()
: <a class="el" href="classOPI_1_1PropertyHandle.php#bf6163044e2c160b24c4314460304aac">OPI::PropertyHandle</a><li>GetInstModCount()
: <a class="el" href="classOPI_1_1PropertyHandle.php#029aad41ffd601344a85286301be48c9">OPI::PropertyHandle</a><li>GetInt()
: <a class="el" href="classOPI_1_1PropertyHandle.php#3f05952ad13e1740c827dbea96137673">OPI::PropertyHandle</a><li>GetIntValue()
: <a class="el" href="classOPI_1_1PropertyHandle.php#985dd4dbf7435d7dcb6172aab71b2042">OPI::PropertyHandle</a><li>GetKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#53525857c4bf042c57d810f51be1ac6c">OPI::PropertyHandle</a><li>GetKeyLength()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9c1d8f654254f2c060e8eff917e96b8d">OPI::PropertyHandle</a><li>GetLastSchemaVersion()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#3b5c0df485f53a22dc7549705bfd21cf">OPI::DatabaseHandle</a><li>GetLOID()
: <a class="el" href="classOPI_1_1PropertyHandle.php#405e19af3cf60c6ee681895714fb0538">OPI::PropertyHandle</a><li>GetLOIDByKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#e2d7e76c49d241ea4b7672938ffc4545">OPI::PropertyHandle</a><li>GetMinutes()
: <a class="el" href="classOPI_1_1PropertyHandle.php#17442eb0b34da2a243ed119fd0eccaaf">OPI::PropertyHandle</a><li>GetMode()
: <a class="el" href="classOPI_1_1PropertyHandle.php#7e3144c5a65b1ba9168a250b7562b168">OPI::PropertyHandle</a><li>GetMonth()
: <a class="el" href="classOPI_1_1PropertyHandle.php#61864306d9987aa0b44d260788472224">OPI::PropertyHandle</a><li>getName()
: <a class="el" href="classOPI_1_1Session.php#79d3a071099b435365c64d0c3be3cd05">OPI::Session</a><li>GetNormalized()
: <a class="el" href="classOPI_1_1PropertyHandle.php#39de56c4f01452455e4b53f39a013c6d">OPI::PropertyHandle</a><li>GetObject()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#0e1fcaf305f1bac7edeadc79e9339922">OPI::DBObjectHandle</a><li>GetObjectHandle()
: <a class="el" href="classOPI_1_1PropertyHandle.php#dda23bb5d9165061017ee6d2df163f19">OPI::PropertyHandle</a><li>GetODABAClient()
: <a class="el" href="classOPI_1_1OPIFactory.php#f589ad5d1273282e8ae1a6dfa2374a6d">OPI::OPIFactory</a><li>GetOperationHandle()
: <a class="el" href="classOPI_1_1OPIFactory.php#6061a9ffeda42c0c2e6486de392f6e90">OPI::OPIFactory</a><li>GetOrigin()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d96f63ec69c25f46ad2562984e40e094">OPI::PropertyHandle</a><li>GetParentProperty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#2c78b262d499699ad099888bd5476b67">OPI::PropertyHandle</a><li>GetPath()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#7a444ce042f04d66699ce950515af348">OPI::DBObjectHandle</a><li>GetPort()
: <a class="el" href="classOPI_1_1ODABAClient.php#4b3b22489fb5ec8ae08af933ce29f7bc">OPI::ODABAClient</a><li>GetPropertyHandle()
: <a class="el" href="classOPI_1_1OPIFactory.php#5bbbff584d64fb1ca1cbeb16a1a1d709">OPI::OPIFactory</a>, <a class="el" href="classOPI_1_1PropertyHandle.php#6f6182898cfd71cf08aff0a90caa6c1d">OPI::PropertyHandle</a><li>GetPropertyPath()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0698409c7e09e24684891ada346adabf">OPI::PropertyHandle</a><li>GetReference()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a00b8fa4ecd082112ddc967cf0b27145">OPI::PropertyHandle</a><li>GetRefModCount()
: <a class="el" href="classOPI_1_1PropertyHandle.php#bb6297b632fe869d8fa694478e5142df">OPI::PropertyHandle</a><li>GetRelative()
: <a class="el" href="classOPI_1_1PropertyHandle.php#049b9741a307dd82222e54a9f8e2dc84">OPI::PropertyHandle</a><li>GetRelativeCount()
: <a class="el" href="classOPI_1_1PropertyHandle.php#bcacb7de5e36a5b160a5d60a475aac20">OPI::PropertyHandle</a><li>GetRelativeIndex()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ca7923ecb9fb3ecdfff82406f80eaa89">OPI::PropertyHandle</a><li>GetResult()
: <a class="el" href="classOPI_1_1OperationHandle.php#bf0503f42ed5bbb2cbf112843002eefb">OPI::OperationHandle</a><li>GetSchemaVersion()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#ab129a9a81806ea2c2bde6dac1b87602">OPI::DBObjectHandle</a><li>GetSeconds()
: <a class="el" href="classOPI_1_1PropertyHandle.php#f09dfecf3aaea5b68610e0a483e70920">OPI::PropertyHandle</a><li>GetSelectedKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1b7ae3ad5c9d99e1439bd5dbc23fc402">OPI::PropertyHandle</a><li>GetServerVariable()
: <a class="el" href="classOPI_1_1ODABAClient.php#c9c00160c3ca3c7a7e4302fcf62bbecc">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#05497af3f37d46ab29468959feee0a51">OPI::DBObjectHandle</a><li>GetSize()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a1944f236f18db77a5c903415a5127ca">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1OperationHandle.php#e7c251c9b2a474c210eea06b52a2392c">OPI::OperationHandle</a><li>GetSizeOf()
: <a class="el" href="classOPI_1_1PropertyHandle.php#2504375c98a0c16dc938f417e520b457">OPI::PropertyHandle</a><li>GetSortKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#feb951465fe83c9d131eab6651212466">OPI::PropertyHandle</a><li>GetSortKeyLength()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d0766eb4a9220a3086e02dcd3247cb15">OPI::PropertyHandle</a><li>GetString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#8748b316d0d5f4079158fe70608c0071">OPI::PropertyHandle</a><li>GetStringLength()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1524da891ff83a92d3757ed0b72ed719">OPI::PropertyHandle</a><li>GetStringValue()
: <a class="el" href="classOPI_1_1PropertyHandle.php#fc5512b7bc716dd3f1092f1b53ec1215">OPI::PropertyHandle</a><li>GetSubString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#2d8b4d398eff23c6aea44c81d0961449">OPI::PropertyHandle</a><li>GetSystemVersion()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#613112df1b226847c6528fb43e8f73e3">OPI::DBObjectHandle</a><li>GetTempName()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#5ce7edc788f7a7db483c01d1a3079f02">OPI::DatabaseHandle</a><li>GetText()
: <a class="el" href="classOPI_1_1PropertyHandle.php#979ec0942bb63626db53910164497ce7">OPI::PropertyHandle</a><li>GetTime()
: <a class="el" href="classOPI_1_1PropertyHandle.php#5fe3f32628060878d0150e29e19d5eaf">OPI::PropertyHandle</a><li>GetTimeStamp()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#3185d9ae7b083988ad49d0baf92aa5a2">OPI::DBObjectHandle</a><li>GetTransactionLevel()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#25d64f0ab757a136d0130d26ba0034e6">OPI::DBObjectHandle</a><li>GetType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#363b40b9e43f55a26fc0dacd725ee34d">OPI::PropertyHandle</a><li>GetValid()
: <a class="el" href="classOPI_1_1PropertyHandle.php#8a894038082afd43d7d506c50bb7a890">OPI::PropertyHandle</a><li>GetVersion()
: <a class="el" href="classOPI_1_1PropertyHandle.php#90d3e52c0c9464a4be0457590ae3d2d4">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#c02df2f3e5fc8e9e8d8dba4a088d7a8c">OPI::DBObjectHandle</a><li>GetVersionString()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#8077a7e3481699d6e63ba6e75286fe63">OPI::DBObjectHandle</a><li>GetWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#bb88598fd54f1d8ff199ae0ffab9da9f">OPI::DBObjectHandle</a><li>GetYear()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ca415d961c17bd655037f8b0613e83cc">OPI::PropertyHandle</a><li>Group()
: <a class="el" href="classOPI_1_1PropertyHandle.php#c4d23f049984e72833b4eaaf959f5f4d">OPI::PropertyHandle</a></ul>
<? include "layout/foot.inc.php";?>
