<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="functions.php"><span>All</span></a></li>
    <li id="current"><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions_func.php#index_a"><span>a</span></a></li>
    <li><a href="functions_func_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_func_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_func_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_func_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_func_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_func_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_func_0x68.php#index_h"><span>h</span></a></li>
    <li id="current"><a href="functions_func_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_func_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_func_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_func_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_func_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_func_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_func_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_func_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_func_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_func_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_func_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_func_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
&nbsp;
<p>
<h3><a class="anchor" name="index_i">- i -</a></h3><ul>
<li>IgnoreWriteProtect()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#9aec52613897077b4454b52fbaadae4f">OPI::DBObjectHandle</a><li>Inherits()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1726049c6103b5a682ca371a4e53c4c2">OPI::PropertyHandle</a><li>InitDataArea()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#9fc6adda90478577a13ad33a29ab50ec">OPI::DBObjectHandle</a><li>Initialize()
: <a class="el" href="classOPI_1_1ODABAClient.php#b11f07d0119f695c4b94aa7a4c49a984">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1CheckOptions.php#7d6501a9f8ca2aaf96e1a2cca2827f0e">OPI::CheckOptions</a><li>InitMainBase()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#994a75367b38a4aa1c55810541502eb5">OPI::DBObjectHandle</a><li>InitSubBase()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#9ab2aec8269f682b29dc0d856aaf972e">OPI::DBObjectHandle</a><li>InsertString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#5c970bb0ea4cc1b07f946bd592106d98">OPI::PropertyHandle</a><li>InsertTerminator()
: <a class="el" href="classOPI_1_1PropertyHandle.php#8a270f97d5031135afb76535fd5e63d6">OPI::PropertyHandle</a><li>InstanceInserted()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9c88f2008ec4b6f7b2d60371d19f0e0e">OPI::PropertyHandle</a><li>InstanceToString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1c218342d220a0ba6b1620e9a935de6a">OPI::PropertyHandle</a><li>Intersect()
: <a class="el" href="classOPI_1_1PropertyHandle.php#52fe02754466839ec48a66f0559e423a">OPI::PropertyHandle</a><li>Is()
: <a class="el" href="classOPI_1_1PropertyHandle.php#4948a4d5b80de712f14ce1db1af16823">OPI::PropertyHandle</a><li>IsA()
: <a class="el" href="classOPI_1_1PropertyHandle.php#f3083afbcc9a76c79bc46bf0f4a1e47f">OPI::PropertyHandle</a><li>IsActive()
: <a class="el" href="classOPI_1_1PropertyHandle.php#f6c7d85ff6ab6726d884674fb9f67707">OPI::PropertyHandle</a><li>IsAttribute()
: <a class="el" href="classOPI_1_1PropertyHandle.php#714ec881322b738ad8ec7785d5943427">OPI::PropertyHandle</a><li>IsAutoSelection()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0377ea77ec5028ed8a40483747346bb2">OPI::PropertyHandle</a><li>IsBasedOn()
: <a class="el" href="classOPI_1_1PropertyHandle.php#231598b4d8b5fbee6e8b939cd401ec34">OPI::PropertyHandle</a><li>IsBasetypeProperty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#26bdd1307bf91febff6332fac0da38d9">OPI::PropertyHandle</a><li>IsBasicType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#762ec670b7a426ac96e9a0dd08cf7059">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DatabaseHandle.php#2a20069aec468450b355e01e2d442fc5">OPI::DatabaseHandle</a><li>IsClient()
: <a class="el" href="classOPI_1_1PropertyHandle.php#50eab020482eb42bfca5c1f4e852d9c0">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#4a50406504d095607cda8b56cad62aee">OPI::DBObjectHandle</a><li>IsCollection()
: <a class="el" href="classOPI_1_1PropertyHandle.php#56887bf9d247355aa79d8bbf692f90f8">OPI::PropertyHandle</a><li>IsCollectionUpdate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#09a7ed92e776e8ff87730e61bfe6bf1a">OPI::PropertyHandle</a><li>IsConnected()
: <a class="el" href="classOPI_1_1ODABAClient.php#8210c176157484620dfc7317cf3e3e0f">OPI::ODABAClient</a><li>IsCopyHandle()
: <a class="el" href="classOPI_1_1PropertyHandle.php#bd51627f9f7a6efb14fd5dacc280eea3">OPI::PropertyHandle</a><li>IsDirty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9aa870f9f56967751cd62c4f86b35d1a">OPI::PropertyHandle</a><li>IsEmpty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a1d3bcf8b065ca568ada71008b9a8979">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#74bb81725de0d27d6449f3266e62239b">OPI::DBObjectHandle</a><li>IsEnumeration()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ff00d2071beb83265ee1add10fc2264c">OPI::PropertyHandle</a><li>IsGenericAttribute()
: <a class="el" href="classOPI_1_1PropertyHandle.php#92e05419943e27c9ee206aa368fd181e">OPI::PropertyHandle</a><li>IsInitInstance()
: <a class="el" href="classOPI_1_1PropertyHandle.php#cf21abafda484e4d4a25f20b413cf44d">OPI::PropertyHandle</a><li>IsLicenced()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#eb2def9f4043e46a54b0f333a6338b3f">OPI::DBObjectHandle</a><li>IsMemo()
: <a class="el" href="classOPI_1_1PropertyHandle.php#09ae183fa1e35ca453cba04eb4ccfdc6">OPI::PropertyHandle</a><li>IsModified()
: <a class="el" href="classOPI_1_1PropertyHandle.php#5d62701d933fa182f146a13c9d311ac4">OPI::PropertyHandle</a><li>IsNewInstance()
: <a class="el" href="classOPI_1_1PropertyHandle.php#00af7e5a4976c0e9a674c8a35fdd5b83">OPI::PropertyHandle</a><li>IsNumeric()
: <a class="el" href="classOPI_1_1PropertyHandle.php#23836c41ded2cdb34db8fd6daba215e8">OPI::PropertyHandle</a><li>IsOldInstance()
: <a class="el" href="classOPI_1_1PropertyHandle.php#69d31b51a5f5261ffd8c552eb755e865">OPI::PropertyHandle</a><li>IsOpened()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#5e244effdda607f09005139c0c8ab8a3">OPI::DBObjectHandle</a><li>IsOwner()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1f1222599dc272b48d66865f2442fec9">OPI::PropertyHandle</a><li>IsPositioned()
: <a class="el" href="classOPI_1_1PropertyHandle.php#8f2ed7305788e0385ef7cf6d4ef3e5b2">OPI::PropertyHandle</a><li>IsReadOnly()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a82c3daa1c6b859446d68cbd2b4a69c2">OPI::PropertyHandle</a><li>IsSelected()
: <a class="el" href="classOPI_1_1PropertyHandle.php#100ccbf5da310f72d6e9e21ecf10ab1b">OPI::PropertyHandle</a><li>IsSensitive()
: <a class="el" href="classOPI_1_1PropertyHandle.php#c07d2a9cdf921fed4d4ee48ecb0beffa">OPI::PropertyHandle</a><li>IsServer()
: <a class="el" href="classOPI_1_1PropertyHandle.php#462eb3f5015a79488a28f8f6845f928e">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#3a98592b40d174737ff1c76c9dc64604">OPI::DBObjectHandle</a><li>IsShareBaseHandle()
: <a class="el" href="classOPI_1_1PropertyHandle.php#f850b4bcf45c22c3738f3ea680a11b1f">OPI::PropertyHandle</a><li>IsShared()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#06441314e3fc496a06d43713185dd88c">OPI::DBObjectHandle</a><li>IsStructure()
: <a class="el" href="classOPI_1_1PropertyHandle.php#be8622f649e02242c11e12ef5c0d0e7b">OPI::PropertyHandle</a><li>IsText()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a4eb107dbe39bd9bd1845ad0900afa0f">OPI::PropertyHandle</a><li>IsTransient()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0c08326c1c123f7405b4444b97d61c25">OPI::PropertyHandle</a><li>IsTrue()
: <a class="el" href="classOPI_1_1PropertyHandle.php#3a9a392c924155d552727e86d7388614">OPI::PropertyHandle</a><li>IsTyped()
: <a class="el" href="classOPI_1_1PropertyHandle.php#5178f923fa95fc8b34c9ef43e1a3a5bb">OPI::PropertyHandle</a><li>IsUserHandle()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9afe52ed14a3b4d4b1e2b595140e3096">OPI::PropertyHandle</a><li>IsValid()
: <a class="el" href="classOPI_1_1PropertyHandle.php#55f03e1028726ec0d85f8179a1fc1ab1">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1OperationHandle.php#515945497dc0c8a5014632585a0ac7ef">OPI::OperationHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#fd587cecb9579940cf65876d7d864fed">OPI::DBObjectHandle</a><li>IsValidText()
: <a class="el" href="classOPI_1_1PropertyHandle.php#39bb4432fa5544b1c27f34898260658a">OPI::PropertyHandle</a><li>IsVariableType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9fb026b8e4ff479edcdef553980788b5">OPI::PropertyHandle</a><li>IsWeakTyped()
: <a class="el" href="classOPI_1_1PropertyHandle.php#cc8be938f523cbb5c0bfef696098a501">OPI::PropertyHandle</a><li>IsWrite()
: <a class="el" href="classOPI_1_1PropertyHandle.php#76aafaad3ed5b2283e5dea5563b9c756">OPI::PropertyHandle</a></ul>
<? include "layout/foot.inc.php";?>
