<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="functions.php"><span>All</span></a></li>
    <li id="current"><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions_func.php#index_a"><span>a</span></a></li>
    <li><a href="functions_func_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_func_0x63.php#index_c"><span>c</span></a></li>
    <li id="current"><a href="functions_func_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_func_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_func_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_func_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_func_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_func_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_func_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_func_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_func_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_func_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_func_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_func_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_func_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_func_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_func_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_func_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_func_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
&nbsp;
<p>
<h3><a class="anchor" name="index_d">- d -</a></h3><ul>
<li>DeactivateShadowBase()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#bc72096139d42972bad6abdd519abe99">OPI::DBObjectHandle</a><li>Delete()
: <a class="el" href="classOPI_1_1PropertyHandle.php#4df2b3f5d3c4738ac629de43f41e7073">OPI::PropertyHandle</a><li>DeleteByKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#c4e9fce9125a60fbd36099b7ffd85782">OPI::PropertyHandle</a><li>DeleteEnum()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#e5e6685c421efccd932489844031211d">OPI::DatabaseHandle</a><li>DeleteExtent()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#295ef1301f357d71f9409ec3580478d5">OPI::DBObjectHandle</a><li>DeleteExtentRef()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#9b86a7c8b3034459398a66504f9e2769">OPI::DBObjectHandle</a><li>DeleteIndexEntry()
: <a class="el" href="classOPI_1_1PropertyHandle.php#dc8cb9fbf4826913897e5265e09d5376">OPI::PropertyHandle</a><li>DeleteOnPosition()
: <a class="el" href="classOPI_1_1PropertyHandle.php#11e5b947b193ab2e0ed9b9eab6404cf4">OPI::PropertyHandle</a><li>DeleteSet()
: <a class="el" href="classOPI_1_1PropertyHandle.php#63d335c37ceaf828feb3afa4f6ac6a57">OPI::PropertyHandle</a><li>DeleteWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#d6e64857beeff5902de88860240c2afe">OPI::DBObjectHandle</a><li>Destroy()
: <a class="el" href="classOPI_1_1Session.php#865bfa929564dba4c4d0608094bce427">OPI::Session</a>, <a class="el" href="classOPI_1_1OPIFactory.php#31abc14be2bbefc6ebd72e72b5b3066e">OPI::OPIFactory</a><li>DictDisplay()
: <a class="el" href="classOPI_1_1ODABAClient.php#2702357dbffadb760a79068cf4226110">OPI::ODABAClient</a><li>DisableEventHandling()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#ecbd245548e7e981a8c075cbac71f1d9">OPI::DBObjectHandle</a><li>DisableKeyCheck()
: <a class="el" href="classOPI_1_1PropertyHandle.php#40f5bd74d73c2ca2ea777fcd061f2ad3">OPI::PropertyHandle</a><li>DisableWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#294bf5a5d38bd2fd71ba1ade6c7bddc5">OPI::DBObjectHandle</a><li>DiscardWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#7217ed051166028205a9a80ddd83d0f7">OPI::DBObjectHandle</a><li>Disconnect()
: <a class="el" href="classOPI_1_1ODABAClient.php#ff71769a50a6a9df91d2aaca7b926343">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DataSourceHandle.php#6ce9a3b75e9400fe258312c857da8e5f">OPI::DataSourceHandle</a><li>Duplicate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9be8acc1bd2dd0c86ae3c58115fb1608">OPI::PropertyHandle</a><li>DuplicateKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0ed17cc88a76e6714faa223cc7b236ad">OPI::PropertyHandle</a></ul>
<? include "layout/foot.inc.php";?>
