<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li id="current"><a href="functions.php"><span>All</span></a></li>
    <li><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions.php#index_a"><span>a</span></a></li>
    <li><a href="functions_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_0x72.php#index_r"><span>r</span></a></li>
    <li id="current"><a href="functions_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
Here is a list of all class members with links to the classes they belong to:
<p>
<h3><a class="anchor" name="index_s">- s -</a></h3><ul>
<li>Save()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9784a0d27932c7ab91ad5ed9746907ba">OPI::PropertyHandle</a><li>SearchText()
: <a class="el" href="classOPI_1_1PropertyHandle.php#2e16ae83f35d2c115c0c3acd68af5096">OPI::PropertyHandle</a><li>Select()
: <a class="el" href="classOPI_1_1PropertyHandle.php#528852a72108f3077e4c7dc66af2f9bf">OPI::PropertyHandle</a><li>SendClientMessage()
: <a class="el" href="classOPI_1_1ODABAClient.php#c6889226d99c230ee3b3abd971151ef7">OPI::ODABAClient</a><li>SetActionResult()
: <a class="el" href="classOPI_1_1PropertyHandle.php#effb703235add492a8bd389cd0100f98">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#28042ad553dca1447810d9335714aa6d">OPI::DBObjectHandle</a><li>SetContextVariables()
: <a class="el" href="classOPI_1_1PropertyHandle.php#cc272f515a721d090a9278d402877b56">OPI::PropertyHandle</a><li>SetDatabase()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#1cf18944e68a651dd2e604e9b632de00">OPI::DataSourceHandle</a><li>SetDataSource()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#aeab7def6748b3b8e781d865af380af7">OPI::DataSourceHandle</a><li>SetDBObject()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#fbdd65acbeff5638995db1f27c284adb">OPI::DataSourceHandle</a><li>SetDictionary()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#c9a870f7f350e12388e47aed7d88987a">OPI::DataSourceHandle</a><li>SetDirty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#cd16da0067eba685c00b29b012d4c027">OPI::PropertyHandle</a><li>SetDynLength()
: <a class="el" href="classOPI_1_1PropertyHandle.php#2bdd298ecaa88a614add810e59cc2a06">OPI::PropertyHandle</a><li>SetGenAttribute()
: <a class="el" href="classOPI_1_1PropertyHandle.php#6a697a21bda9ec33d0d30009c4f4d8c8">OPI::PropertyHandle</a><li>SetKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#4daf9fadbae902857e93f94d4f3f7f56">OPI::PropertyHandle</a><li>SetModified()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a7f755847be4c70558f746b129e53229">OPI::PropertyHandle</a><li>SetNormalized()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0a62444a334c3766fe8c57a9d367d9fa">OPI::PropertyHandle</a><li>SetOrder()
: <a class="el" href="classOPI_1_1PropertyHandle.php#36781851115bcf6759b4504260604573">OPI::PropertyHandle</a><li>SetOverload()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#cca518062f19b85c07de34c6da500dde">OPI::DBObjectHandle</a><li>SetResourceDB()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#dab943e9899812dbee1a0c28eb9a9400">OPI::DataSourceHandle</a><li>SetSelection()
: <a class="el" href="classOPI_1_1PropertyHandle.php#665acb8397950abee23e959ae646ef2a">OPI::PropertyHandle</a><li>SetServerVariable()
: <a class="el" href="classOPI_1_1ODABAClient.php#160daf8ba319e0ccf9536da868308768">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#e2398eca3ddf53f97190be3002ea26ec">OPI::DBObjectHandle</a><li>SetSortKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#54bd9e639f6d69ca7e5e1b24a6c5cb15">OPI::PropertyHandle</a><li>SetTransientProperty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0f3e479bc9acc52f9927eb68816643a7">OPI::PropertyHandle</a><li>SetType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d3e381d3e1615ee2be7b02950451da5d">OPI::PropertyHandle</a><li>Setup()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#b9f4f98d9b237b14164aba219e22d826">OPI::DataSourceHandle</a><li>SetUpdate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#e635b81c13577c6e396132d8134b8e13">OPI::PropertyHandle</a><li>SetupTypeID()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#3a07045216b382d07ad340ee7d2d6168">OPI::DBObjectHandle</a><li>SetupVariables()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#2a90e028b8046158b8fc043f507e3d4f">OPI::DataSourceHandle</a><li>SetUserDefinedIdentity()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#eaa97345923ec5b6b191568865a2d306">OPI::DBObjectHandle</a><li>SetValue()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d87f3c6d4abe5917f37b8675a43c0255">OPI::PropertyHandle</a><li>SetValueBigInt()
: <a class="el" href="classOPI_1_1PropertyHandle.php#5b0ea207edeb6a4a2135340fe8f1deef">OPI::PropertyHandle</a><li>SetValueBoolean()
: <a class="el" href="classOPI_1_1PropertyHandle.php#907822aada0ed6cda656a97f9a36672d">OPI::PropertyHandle</a><li>SetValueDate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#fcaf09011e068f21da6ae9ed123e2566">OPI::PropertyHandle</a><li>SetValueFloat()
: <a class="el" href="classOPI_1_1PropertyHandle.php#e1e73bf4250fb81c0439b5091f610562">OPI::PropertyHandle</a><li>SetValueInteger()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1d1efdeba3d32ec4a49656b26dcb957f">OPI::PropertyHandle</a><li>SetValueString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#c4c9224a4a47689dc9a18b4a90eee047">OPI::PropertyHandle</a><li>SetValueTime()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a077c2db86e0536ce1e5c4a73706afc1">OPI::PropertyHandle</a><li>SetValueTimestamp()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ade4cd634ea700bdc9ff6e8afdcfe816">OPI::PropertyHandle</a><li>SetVariables()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#c5bebdd3618c21d0b1172b7a96ded3fa">OPI::DataSourceHandle</a><li>SetVersion()
: <a class="el" href="classOPI_1_1PropertyHandle.php#6f5d89300e3bed24307824e5b72b44a6">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#8bb15ae929b12ad33f48dbfda37fa70e">OPI::DBObjectHandle</a><li>SetVersioni1()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#60f2af2feeac675830aac48169aded3f">OPI::DBObjectHandle</a><li>SetVersioni2()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#f1a3840f3d2cff6058195af7dbcf8e95">OPI::DBObjectHandle</a><li>SetWProtect()
: <a class="el" href="classOPI_1_1PropertyHandle.php#6110cd34a718d9e72c7ce0d042411acb">OPI::PropertyHandle</a><li>ShutDown()
: <a class="el" href="classOPI_1_1ODABAClient.php#4c6df86135128a2318e915eeb25ce8b7">OPI::ODABAClient</a><li>shutdown()
: <a class="el" href="classOPI_1_1SessionFactory.php#46088a0a1aaae66c6c175c8658b7e892">OPI::SessionFactory</a><li>StartPause()
: <a class="el" href="classOPI_1_1ODABAClient.php#40895c5380f29d5abb352b61f7a65179">OPI::ODABAClient</a><li>StatDisplay()
: <a class="el" href="classOPI_1_1ODABAClient.php#51847fd895b42e299cde7508e40bee08">OPI::ODABAClient</a><li>StopPause()
: <a class="el" href="classOPI_1_1ODABAClient.php#63bb40a9e1fda4bc5abe9d67df9a2b0f">OPI::ODABAClient</a><li>StringToEnum()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#47d0534fc569f5665f9135d640f7ffee">OPI::DatabaseHandle</a><li>SysInfoDisplay()
: <a class="el" href="classOPI_1_1ODABAClient.php#657337d6de75b37462deaa61e22db2da">OPI::ODABAClient</a></ul>
<? include "layout/foot.inc.php";?>
