<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="functions.php"><span>All</span></a></li>
    <li id="current"><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions_func.php#index_a"><span>a</span></a></li>
    <li id="current"><a href="functions_func_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_func_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_func_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_func_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_func_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_func_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_func_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_func_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_func_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_func_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_func_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_func_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_func_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_func_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_func_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_func_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_func_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_func_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_func_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
&nbsp;
<p>
<h3><a class="anchor" name="index_b">- b -</a></h3><ul>
<li>BackupDB()
: <a class="el" href="classOPI_1_1ODABAClient.php#29a225b7f69ccf39a9fdc7e558d0415f">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#66be6d3c53b7486a2b153fdd44e38a9e">OPI::DBObjectHandle</a><li>BaseType()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#fbf1c5cb85150d8f1d781cb8b5e83fa3">OPI::DatabaseHandle</a><li>BeginTransaction()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#9df3759f8375d06758082a93be18fe26">OPI::DataSourceHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#a7213f4e061d5f091771bf4fdedf6748">OPI::DBObjectHandle</a></ul>
<? include "layout/foot.inc.php";?>
