<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li id="current"><a href="functions.php"><span>All</span></a></li>
    <li><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions.php#index_a"><span>a</span></a></li>
    <li><a href="functions_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_0x70.php#index_p"><span>p</span></a></li>
    <li id="current"><a href="functions_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
Here is a list of all class members with links to the classes they belong to:
<p>
<h3><a class="anchor" name="index_r">- r -</a></h3><ul>
<li>RecreateExtent()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#d04a9928607285788667f897798101c6">OPI::DBObjectHandle</a><li>Refresh()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ce107678ec14ea26019aa1f04b40336c">OPI::PropertyHandle</a><li>ReleaseBuffer()
: <a class="el" href="classOPI_1_1PropertyHandle.php#f6163ec5d7f7831fffb3a791cf47abed">OPI::PropertyHandle</a><li>RemoveFromCollection()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9ab6e4393c2db5a468e51ef20d92a8a2">OPI::PropertyHandle</a><li>RemoveString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#afaad17eb070ec78a4ffe16353369a2b">OPI::PropertyHandle</a><li>RemoveTerminator()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d25ec7c64ca56a54036bc405de8d8f81">OPI::PropertyHandle</a><li>Rename()
: <a class="el" href="classOPI_1_1PropertyHandle.php#afcaffbe267dfcf35caff9ad6e69a245">OPI::PropertyHandle</a><li>RepairIndex()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a672d09d5640240d9682b74091c8f88c">OPI::PropertyHandle</a><li>ReplaceString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#bf8a0822c38871f6e610653b792ea19d">OPI::PropertyHandle</a><li>ReplaceSysVariables()
: <a class="el" href="classOPI_1_1PropertyHandle.php#eee609cd6e6c4b052a1c5946140cd785">OPI::PropertyHandle</a><li>Reset()
: <a class="el" href="classOPI_1_1PropertyHandle.php#c3992a23129bf8a9f1d1bb7bbda7f304">OPI::PropertyHandle</a><li>ResetDirty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#b43bc7cdab9c6ee5d47464e3d1492469">OPI::PropertyHandle</a><li>ResetTransientProperty()
: <a class="el" href="classOPI_1_1PropertyHandle.php#1034a92cf38130d25f7a52cf287ed286">OPI::PropertyHandle</a><li>ResetWProtect()
: <a class="el" href="classOPI_1_1PropertyHandle.php#972cba1aea02fc37093633214aedd6a2">OPI::PropertyHandle</a><li>RestoreDB()
: <a class="el" href="classOPI_1_1ODABAClient.php#8484d92d7ae22f0648690c3ab7c8e16a">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#67f5fc2080584732e725fe399dfcb1bf">OPI::DBObjectHandle</a><li>RollBack()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#88ce92d64b920eef8b9a05aad3ed7f64">OPI::DataSourceHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#366a75e5ed3a466ad96eb515815a618d">OPI::DBObjectHandle</a></ul>
<? include "layout/foot.inc.php";?>
