<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="functions.php"><span>All</span></a></li>
    <li id="current"><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions_func.php#index_a"><span>a</span></a></li>
    <li><a href="functions_func_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_func_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_func_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_func_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_func_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_func_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_func_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_func_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_func_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_func_0x6c.php#index_l"><span>l</span></a></li>
    <li id="current"><a href="functions_func_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_func_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_func_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_func_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_func_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_func_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_func_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_func_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_func_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
&nbsp;
<p>
<h3><a class="anchor" name="index_m">- m -</a></h3><ul>
<li>MarkUnused()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d90ad8985563c31b9818c7c518380140">OPI::PropertyHandle</a><li>MarkUsed()
: <a class="el" href="classOPI_1_1PropertyHandle.php#592d6fe90304cf0f1bfbd7f8c45558d2">OPI::PropertyHandle</a><li>Minus()
: <a class="el" href="classOPI_1_1PropertyHandle.php#815816b8ce93245b721f8b1e124780c2">OPI::PropertyHandle</a><li>Modify()
: <a class="el" href="classOPI_1_1PropertyHandle.php#530da1bc3fd621491cac460cdb324e65">OPI::PropertyHandle</a><li>Move()
: <a class="el" href="classOPI_1_1PropertyHandle.php#b85a315719eabb51295920475f23842d">OPI::PropertyHandle</a><li>MoveDown()
: <a class="el" href="classOPI_1_1PropertyHandle.php#f224027934158d3c38c78b052156e4f9">OPI::PropertyHandle</a><li>MoveUp()
: <a class="el" href="classOPI_1_1PropertyHandle.php#cb87176a5729656d33b3ec165b78acfe">OPI::PropertyHandle</a></ul>
<? include "layout/foot.inc.php";?>
