<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="functions.php"><span>All</span></a></li>
    <li id="current"><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions_func.php#index_a"><span>a</span></a></li>
    <li><a href="functions_func_0x62.php#index_b"><span>b</span></a></li>
    <li><a href="functions_func_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_func_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_func_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_func_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_func_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_func_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_func_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_func_0x6b.php#index_k"><span>k</span></a></li>
    <li id="current"><a href="functions_func_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_func_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_func_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_func_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_func_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_func_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_func_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_func_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_func_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_func_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
&nbsp;
<p>
<h3><a class="anchor" name="index_l">- l -</a></h3><ul>
<li>Locate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#513a27b66e47280ac6b26c85cc4388d1">OPI::PropertyHandle</a><li>LocatePath()
: <a class="el" href="classOPI_1_1PropertyHandle.php#0594af24234953ae45e7d24142a39aca">OPI::PropertyHandle</a><li>LocateWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#0af77aad9b9e4fbbb6cd7186b3be5a5e">OPI::DBObjectHandle</a><li>Lock()
: <a class="el" href="classOPI_1_1PropertyHandle.php#880ff7b45a65894b1d20d75c90235554">OPI::PropertyHandle</a><li>LockSet()
: <a class="el" href="classOPI_1_1PropertyHandle.php#06cb7fc442ff07c7e48b2a4034aa6868">OPI::PropertyHandle</a></ul>
<? include "layout/foot.inc.php";?>
