<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li id="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li id="current"><a href="functions.php"><span>All</span></a></li>
    <li><a href="functions_func.php"><span>Functions</span></a></li>
  </ul>
</div>
<div class="tabs">
  <ul>
    <li><a href="functions.php#index_a"><span>a</span></a></li>
    <li><a href="functions_0x62.php#index_b"><span>b</span></a></li>
    <li id="current"><a href="functions_0x63.php#index_c"><span>c</span></a></li>
    <li><a href="functions_0x64.php#index_d"><span>d</span></a></li>
    <li><a href="functions_0x65.php#index_e"><span>e</span></a></li>
    <li><a href="functions_0x66.php#index_f"><span>f</span></a></li>
    <li><a href="functions_0x67.php#index_g"><span>g</span></a></li>
    <li><a href="functions_0x68.php#index_h"><span>h</span></a></li>
    <li><a href="functions_0x69.php#index_i"><span>i</span></a></li>
    <li><a href="functions_0x6b.php#index_k"><span>k</span></a></li>
    <li><a href="functions_0x6c.php#index_l"><span>l</span></a></li>
    <li><a href="functions_0x6d.php#index_m"><span>m</span></a></li>
    <li><a href="functions_0x6e.php#index_n"><span>n</span></a></li>
    <li><a href="functions_0x6f.php#index_o"><span>o</span></a></li>
    <li><a href="functions_0x70.php#index_p"><span>p</span></a></li>
    <li><a href="functions_0x72.php#index_r"><span>r</span></a></li>
    <li><a href="functions_0x73.php#index_s"><span>s</span></a></li>
    <li><a href="functions_0x74.php#index_t"><span>t</span></a></li>
    <li><a href="functions_0x75.php#index_u"><span>u</span></a></li>
    <li><a href="functions_0x76.php#index_v"><span>v</span></a></li>
  </ul>
</div>

<p>
Here is a list of all class members with links to the classes they belong to:
<p>
<h3><a class="anchor" name="index_c">- c -</a></h3><ul>
<li>Cancel()
: <a class="el" href="classOPI_1_1PropertyHandle.php#b20129fea8601f6c45911915756aa526">OPI::PropertyHandle</a><li>CancelBuffer()
: <a class="el" href="classOPI_1_1PropertyHandle.php#928a2b8ff3d9789c25cd793015a6f927">OPI::PropertyHandle</a><li>ChangeBuffer()
: <a class="el" href="classOPI_1_1PropertyHandle.php#efff03a48a7e5fa2ba4817b4836ea31b">OPI::PropertyHandle</a><li>ChangeCache()
: <a class="el" href="classOPI_1_1PropertyHandle.php#fc5f6baec1c8a40dfad371c762f61ad3">OPI::PropertyHandle</a><li>ChangeMode()
: <a class="el" href="classOPI_1_1PropertyHandle.php#139763073617041cc7b8537e72c20b6f">OPI::PropertyHandle</a><li>ChangeTimeStamp()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#282b243ab9d9e0e9999cca0880908ac1">OPI::DBObjectHandle</a><li>Check()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d6d1e26560746683089c5f2e9ee203b8">OPI::PropertyHandle</a><li>CheckDB()
: <a class="el" href="classOPI_1_1ODABAClient.php#707abb920b3a8c1c55a315478f7e9ac2">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#cd66f8184161decc49eeccb5d30485ad">OPI::DBObjectHandle</a><li>CheckExpression()
: <a class="el" href="classOPI_1_1OperationHandle.php#b07e2b966e540634484966d0b23ce6f9">OPI::OperationHandle</a>, <a class="el" href="classOPI_1_1DatabaseHandle.php#21bbc8f76e1210608fa2b603e2954578">OPI::DatabaseHandle</a><li>CheckExpressionInClass()
: <a class="el" href="classOPI_1_1OperationHandle.php#5950be1e5d663cbb944b72b9d0b13e4a">OPI::OperationHandle</a>, <a class="el" href="classOPI_1_1DatabaseHandle.php#af5a1d4b9f036e079dbc93e90ecf3549">OPI::DatabaseHandle</a><li>CheckExtentDef()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#f788bbc552027e7c284e7eaf882773c7">OPI::DatabaseHandle</a><li>CheckLicence()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#12492fe8afe759d7eb836c82fbbc29f2">OPI::DBObjectHandle</a><li>CheckPosition()
: <a class="el" href="classOPI_1_1PropertyHandle.php#ffe69436153e2cb0dcdf5a9b8ecde194">OPI::PropertyHandle</a><li>CheckUpdate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#04a51bc78674647edddc87493ed31f34">OPI::PropertyHandle</a><li>CheckValueSet()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#9960f00fa395cbf9c86222155d435295">OPI::DatabaseHandle</a><li>CheckWProtect()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9355288bfdf93506cb353cb8df610530">OPI::PropertyHandle</a><li>Close()
: <a class="el" href="classOPI_1_1PropertyHandle.php#4da25caf3fefb5af810ea97838032834">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1ODABAClient.php#e2abfc2780ed45fd084950abbfccdf28">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DataSourceHandle.php#be97ac8389038827deb649d1537489ac">OPI::DataSourceHandle</a><li>CloseDatabase()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#1f4ae74d7675187f6004242e01bf1d36">OPI::DataSourceHandle</a><li>CloseDBObject()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#caac60818cc967c200585e8ea3fac1ff">OPI::DataSourceHandle</a><li>CloseDictionary()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#4ae6f06d3eafc30d59a1627933c8dbac">OPI::DataSourceHandle</a><li>CloseProperty()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#4aab750640b793b4d924f49e70f27bfa">OPI::DataSourceHandle</a><li>CloseResourceDB()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#4c86c8cfec12266d6f652c1a88b16e6a">OPI::DataSourceHandle</a><li>CloseWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#4faa760d7f53928b59b2efd8ab0ef1a0">OPI::DBObjectHandle</a><li>CommitTransaction()
: <a class="el" href="classOPI_1_1DataSourceHandle.php#44874ce524bb7e57c7cc880bc46538c6">OPI::DataSourceHandle</a>, <a class="el" href="classOPI_1_1DBObjectHandle.php#259fd8b88918356a280746358a5899b7">OPI::DBObjectHandle</a><li>Compare()
: <a class="el" href="classOPI_1_1PropertyHandle.php#e044533a7c78fa124fc1473d904f1086">OPI::PropertyHandle</a><li>CompareDate()
: <a class="el" href="classOPI_1_1PropertyHandle.php#62617a92dffb01d30ad1ceadf2404fa6">OPI::PropertyHandle</a><li>CompareFloat()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a112291e2eb0f7830cb0b0d38279295f">OPI::PropertyHandle</a><li>CompareInteger()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9457638a8a9c9e8888f43d8c3430fe9d">OPI::PropertyHandle</a><li>CompareKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#65fb4aa8b9e97416518737a3967f035f">OPI::PropertyHandle</a><li>CompareSortKey()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9a224aad093a0af3c326dab494f096d4">OPI::PropertyHandle</a><li>CompareString()
: <a class="el" href="classOPI_1_1PropertyHandle.php#6ffbeb99c274213560232bebc6b11309">OPI::PropertyHandle</a><li>CompareTime()
: <a class="el" href="classOPI_1_1PropertyHandle.php#d0e025f9bbf50450a1eb9538075c12dc">OPI::PropertyHandle</a><li>CompareType()
: <a class="el" href="classOPI_1_1PropertyHandle.php#f7d708ca24cc7766bc74f19e5fc3c926">OPI::PropertyHandle</a><li>Connect()
: <a class="el" href="classOPI_1_1ODABAClient.php#676098692dfe4a8ee1bd9ddf0185aa78">OPI::ODABAClient</a>, <a class="el" href="classOPI_1_1DataSourceHandle.php#91980ef0e0976dfc0e78c0c95cbd3a44">OPI::DataSourceHandle</a><li>ConsolidateWorkspace()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#a26908ea8cb842a750965ca8e0a78711">OPI::DBObjectHandle</a><li>Copy()
: <a class="el" href="classOPI_1_1PropertyHandle.php#e70ca6a6183431f65fa4f28302d6a729">OPI::PropertyHandle</a><li>CopyCodeset()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#08407c0798ba9c3938ee736b55832fa5">OPI::DatabaseHandle</a><li>CopyData()
: <a class="el" href="classOPI_1_1PropertyHandle.php#432599f81f6172613234f11468116d5d">OPI::PropertyHandle</a><li>CopyExtentDef()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#7cc11d9508bdb09a116f90878cdc2ee7">OPI::DatabaseHandle</a><li>CopyHandle()
: <a class="el" href="classOPI_1_1PropertyHandle.php#a90b6d7d34af3a733dee8aa58286a7c5">OPI::PropertyHandle</a><li>CopyInstanceArea()
: <a class="el" href="classOPI_1_1PropertyHandle.php#9827f9a2c2b9208b8d678f390c365a3b">OPI::PropertyHandle</a><li>CopySet()
: <a class="el" href="classOPI_1_1PropertyHandle.php#86a2bb091df8b5a612cb7554834cdec3">OPI::PropertyHandle</a><li>CopyStructure()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#f57e690b0c0b2349968a38e7a2d0a498">OPI::DatabaseHandle</a><li>CopyType()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#9f594069f400d9ccf0b6dd3ac9c09e01">OPI::DatabaseHandle</a><li>CreateEnum()
: <a class="el" href="classOPI_1_1DatabaseHandle.php#aa181d097f783d4b1c1b3a20708e7602">OPI::DatabaseHandle</a><li>CreateProxy()
: <a class="el" href="classOPI_1_1SessionFactory.php#629c121574dd4e7ca8818442862933f4">OPI::SessionFactory</a><li>CreateSession()
: <a class="el" href="classOPI_1_1Session.php#c4e79635eba961aa43b967940e705f0c">OPI::Session</a><li>CreateTempExtent()
: <a class="el" href="classOPI_1_1PropertyHandle.php#53279980bac9c98908a829637f12d8db">OPI::PropertyHandle</a>, <a class="el" href="classOPI_1_1DatabaseHandle.php#f5f0041e2765269e0a5b5fb226f89e76">OPI::DatabaseHandle</a><li>CreateTempPropertyHandle()
: <a class="el" href="classOPI_1_1DBObjectHandle.php#654365c6c75847f05cd8f59600b2142f">OPI::DBObjectHandle</a></ul>
<? include "layout/foot.inc.php";?>
