<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li id="current"><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPIICE Class Hierarchy</h1><a href="inherits.php">Go to the graphical class hierarchy</a>
<p>
This inheritance list is sorted roughly, but not completely, alphabetically:<ul>
<li><a class="el" href="classOPI_1_1CheckOptions.php">OPI::CheckOptions</a>
<li><a class="el" href="classOPI_1_1DatabaseHandle.php">OPI::DatabaseHandle</a>
<li><a class="el" href="classOPI_1_1DataSourceHandle.php">OPI::DataSourceHandle</a>
<li><a class="el" href="classOPI_1_1DBObjectHandle.php">OPI::DBObjectHandle</a>
<li><a class="el" href="classOPI_1_1DBObjectHandle.php">OPI::DBObjectHandle</a>
<li><a class="el" href="classOPI_1_1ODABAClient.php">OPI::ODABAClient</a>
<li><a class="el" href="classOPI_1_1OperationHandle.php">OPI::OperationHandle</a>
<li><a class="el" href="classOPI_1_1OPIFactory.php">OPI::OPIFactory</a>
<li><a class="el" href="classOPI_1_1PropertyHandle.php">OPI::PropertyHandle</a>
<li><a class="el" href="classOPI_1_1Session.php">OPI::Session</a>
<li><a class="el" href="classOPI_1_1SessionFactory.php">OPI::SessionFactory</a>
</ul>
<? include "layout/foot.inc.php";?>
