<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li id="current"><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
    <li id="current"><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
    <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPIICE Graphical Class Hierarchy</h1><a href="hierarchy.php">Go to the textual class hierarchy</a>
<p>
<table border="0" cellspacing="10" cellpadding="0">
<tr><td><img src="inherit__graph__0.png" border="0" alt="" usemap="#OPI_1_1CheckOptions_map">
<map name="OPI_1_1CheckOptions_map">
<area href="classOPI_1_1CheckOptions.php" shape="rect" coords="6,5,142,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__1.png" border="0" alt="" usemap="#OPI_1_1DatabaseHandle_map">
<map name="OPI_1_1DatabaseHandle_map">
<area href="classOPI_1_1DatabaseHandle.php" shape="rect" coords="6,5,158,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__2.png" border="0" alt="" usemap="#OPI_1_1DataSourceHandle_map">
<map name="OPI_1_1DataSourceHandle_map">
<area href="classOPI_1_1DataSourceHandle.php" shape="rect" coords="5,5,171,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__3.png" border="0" alt="" usemap="#OPI_1_1DBObjectHandle_map">
<map name="OPI_1_1DBObjectHandle_map">
<area href="classOPI_1_1DBObjectHandle.php" shape="rect" coords="6,5,158,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__4.png" border="0" alt="" usemap="#OPI_1_1DBObjectHandle_map">
<map name="OPI_1_1DBObjectHandle_map">
<area href="classOPI_1_1DBObjectHandle.php" shape="rect" coords="6,5,158,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__5.png" border="0" alt="" usemap="#OPI_1_1ODABAClient_map">
<map name="OPI_1_1ODABAClient_map">
<area href="classOPI_1_1ODABAClient.php" shape="rect" coords="7,5,137,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__6.png" border="0" alt="" usemap="#OPI_1_1OperationHandle_map">
<map name="OPI_1_1OperationHandle_map">
<area href="classOPI_1_1OperationHandle.php" shape="rect" coords="7,5,159,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__7.png" border="0" alt="" usemap="#OPI_1_1OPIFactory_map">
<map name="OPI_1_1OPIFactory_map">
<area href="classOPI_1_1OPIFactory.php" shape="rect" coords="6,5,126,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__8.png" border="0" alt="" usemap="#OPI_1_1PropertyHandle_map">
<map name="OPI_1_1PropertyHandle_map">
<area href="classOPI_1_1PropertyHandle.php" shape="rect" coords="7,5,151,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__9.png" border="0" alt="" usemap="#OPI_1_1Session_map">
<map name="OPI_1_1Session_map">
<area href="classOPI_1_1Session.php" shape="rect" coords="7,5,105,32" alt="">
</map></td></tr>
<tr><td><img src="inherit__graph__10.png" border="0" alt="" usemap="#OPI_1_1SessionFactory_map">
<map name="OPI_1_1SessionFactory_map">
<area href="classOPI_1_1SessionFactory.php" shape="rect" coords="7,5,151,32" alt="">
</map></td></tr>
</table>
<? include "layout/foot.inc.php";?>
