<? include "layout/head.inc.php";?>
<!-- Generated by Doxygen 1.4.6 -->
<div class="tabs">
  <ul>
    <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
    <li id="current"><a href="namespaces.php"><span>Namespaces</span></a></li>
    <li><a href="annotated.php"><span>Classes</span></a></li>
    <li><a href="files.php"><span>Files</span></a></li>
  </ul></div>
<div class="tabs">
  <ul>
    <li><a href="namespaces.php"><span>Namespace List</span></a></li>
    <li><a href="namespacemembers.php"><span>Namespace&nbsp;Members</span></a></li>
  </ul></div>
<h1>OPI Namespace Reference</h1>
<p>
<h2>Classes</h2>
<ul>
<li>class <a class="el" href="classOPI_1_1CheckOptions.php">CheckOptions</a>
<li>class <a class="el" href="classOPI_1_1DBObjectHandle.php">DBObjectHandle</a>
<li>class <a class="el" href="classOPI_1_1DataSourceHandle.php">DataSourceHandle</a>
<li>class <a class="el" href="classOPI_1_1DatabaseHandle.php">DatabaseHandle</a>
<li>class <a class="el" href="classOPI_1_1ODABAClient.php">ODABAClient</a>
<li>class <a class="el" href="classOPI_1_1OperationHandle.php">OperationHandle</a>
<li>class <a class="el" href="classOPI_1_1PropertyHandle.php">PropertyHandle</a>
<li>class <a class="el" href="classOPI_1_1OPIFactory.php">OPIFactory</a>
<li>class <a class="el" href="classOPI_1_1Session.php">Session</a>
<li>class <a class="el" href="classOPI_1_1SessionFactory.php">SessionFactory</a>
</ul>
<h2>Enumerations</h2>
<ul>
<li>enum <a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">PIACC</a> { <a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c041a6ceaf6e131bfcca0b329d61a51ab">piaREAD</a>, 
<a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c353bf6e9c5e548c375a38878be0be112">piaWRITE</a>, 
<a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c6e0407127137221e18171015dfe4b1ad">piaUPDATE</a>, 
<a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c906b4584a9b3f5bd339fea698c5cca6a">piaUNDEFINED</a>
 }
<li>enum <a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf">PIREPL</a> { <br>
&nbsp;&nbsp;<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf4a469d4d7920735fc715784cf13170c4">piaREPLGUID</a>, 
<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf77f4f252f28b8642d8ab8c2f24af1ef8">piaREPLDIRECT</a>, 
<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bfc4f2d3fd96fdc900a039e62b3b1f61a9">piaREPLNONE</a>, 
<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf8da049eb7e3f4a27ee094560398bca78">piaREPLLOCAL</a>, 
<br>
&nbsp;&nbsp;<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf1ab7adc4be55661303a87acccbe47654">piaREPLALL</a>, 
<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf417ed6c1bb6de057d3231c1244a3a1e9">piaREPLINSTANCE</a>, 
<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf740df5595a3907753b87051fc6f7bd96">piaREPLRELATIONSHIPS</a>, 
<a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf24ea37b4fd3393889f3f19cc6eea20dd">piaREPLNOCREATE</a>
<br>
 }
<li>enum <a class="el" href="namespaceOPI.php#289d71610e1123a19421638a59be5a04">PIADEF</a> { <a class="el" href="namespaceOPI.php#289d71610e1123a19421638a59be5a0433845fbd41dea18011f5c02a5e8e42a5">piaUNKNOWN</a>, 
<a class="el" href="namespaceOPI.php#289d71610e1123a19421638a59be5a04b51b0f3c6beaef68e06a0327b5e47b62">piaEXCLUSIVE</a>, 
<a class="el" href="namespaceOPI.php#289d71610e1123a19421638a59be5a04eeea872de7ed970fa35d2c5a17faebd5">piaSHARE</a>
 }
<li>enum <a class="el" href="namespaceOPI.php#f99d2362cb8ceeee7f89f4d7484cac08">ResourceTypes</a> { <a class="el" href="namespaceOPI.php#f99d2362cb8ceeee7f89f4d7484cac0807129435e6c3683a127a7464d82f70dd">resAUTOMATIC</a>, 
<a class="el" href="namespaceOPI.php#f99d2362cb8ceeee7f89f4d7484cac08e32e8bb68f1facd68517d9c15235753b">resSERVER</a>, 
<a class="el" href="namespaceOPI.php#f99d2362cb8ceeee7f89f4d7484cac082b27f61adf8e23957c089f469567e013">resLOCAL</a>, 
<a class="el" href="namespaceOPI.php#f99d2362cb8ceeee7f89f4d7484cac08700d43b8cb141e238b6095d7a2162f5f">resSERVERINTERN</a>
 }
<li>enum <a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a52">ApplicationTypes</a> { <a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a52ef2c717bea5f5cc4e06bca6f9b355a37">aptWINDOWS</a>, 
<a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a5214ff0a6c61856a53698159fc902b5694">aptCONSOLE</a>
 }
</ul>
<hr><h2>Enumeration Type Documentation</h2>
<a class="anchor" name="404bdda975fb800f7c6400da4d6a2a52"></a><!-- doxytag: member="OPI::ApplicationTypes" ref="404bdda975fb800f7c6400da4d6a2a52" args="" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">enum <a class="el" href="namespaceOPI.php#404bdda975fb800f7c6400da4d6a2a52">OPI::ApplicationTypes</a>          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
<dl compact><dt><b>Enumerator: </b></dt><dd>
<table border="0" cellspacing="2" cellpadding="0">
<tr><td valign="top"><em><a class="anchor" name="404bdda975fb800f7c6400da4d6a2a52ef2c717bea5f5cc4e06bca6f9b355a37"></a><!-- doxytag: member="aptWINDOWS" ref="404bdda975fb800f7c6400da4d6a2a52ef2c717bea5f5cc4e06bca6f9b355a37" args="" -->aptWINDOWS</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="404bdda975fb800f7c6400da4d6a2a5214ff0a6c61856a53698159fc902b5694"></a><!-- doxytag: member="aptCONSOLE" ref="404bdda975fb800f7c6400da4d6a2a5214ff0a6c61856a53698159fc902b5694" args="" -->aptCONSOLE</em>&nbsp;</td><td>
</td></tr>
</table>
</dl>
    </td>
  </tr>
</table>
<a class="anchor" name="b6145b86cfe58a7bd071b8a4e538401c"></a><!-- doxytag: member="OPI::PIACC" ref="b6145b86cfe58a7bd071b8a4e538401c" args="" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">enum <a class="el" href="namespaceOPI.php#b6145b86cfe58a7bd071b8a4e538401c">OPI::PIACC</a>          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
<dl compact><dt><b>Enumerator: </b></dt><dd>
<table border="0" cellspacing="2" cellpadding="0">
<tr><td valign="top"><em><a class="anchor" name="b6145b86cfe58a7bd071b8a4e538401c041a6ceaf6e131bfcca0b329d61a51ab"></a><!-- doxytag: member="piaREAD" ref="b6145b86cfe58a7bd071b8a4e538401c041a6ceaf6e131bfcca0b329d61a51ab" args="" -->piaREAD</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="b6145b86cfe58a7bd071b8a4e538401c353bf6e9c5e548c375a38878be0be112"></a><!-- doxytag: member="piaWRITE" ref="b6145b86cfe58a7bd071b8a4e538401c353bf6e9c5e548c375a38878be0be112" args="" -->piaWRITE</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="b6145b86cfe58a7bd071b8a4e538401c6e0407127137221e18171015dfe4b1ad"></a><!-- doxytag: member="piaUPDATE" ref="b6145b86cfe58a7bd071b8a4e538401c6e0407127137221e18171015dfe4b1ad" args="" -->piaUPDATE</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="b6145b86cfe58a7bd071b8a4e538401c906b4584a9b3f5bd339fea698c5cca6a"></a><!-- doxytag: member="piaUNDEFINED" ref="b6145b86cfe58a7bd071b8a4e538401c906b4584a9b3f5bd339fea698c5cca6a" args="" -->piaUNDEFINED</em>&nbsp;</td><td>
</td></tr>
</table>
</dl>
    </td>
  </tr>
</table>
<a class="anchor" name="289d71610e1123a19421638a59be5a04"></a><!-- doxytag: member="OPI::PIADEF" ref="289d71610e1123a19421638a59be5a04" args="" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">enum <a class="el" href="namespaceOPI.php#289d71610e1123a19421638a59be5a04">OPI::PIADEF</a>          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
<dl compact><dt><b>Enumerator: </b></dt><dd>
<table border="0" cellspacing="2" cellpadding="0">
<tr><td valign="top"><em><a class="anchor" name="289d71610e1123a19421638a59be5a0433845fbd41dea18011f5c02a5e8e42a5"></a><!-- doxytag: member="piaUNKNOWN" ref="289d71610e1123a19421638a59be5a0433845fbd41dea18011f5c02a5e8e42a5" args="" -->piaUNKNOWN</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="289d71610e1123a19421638a59be5a04b51b0f3c6beaef68e06a0327b5e47b62"></a><!-- doxytag: member="piaEXCLUSIVE" ref="289d71610e1123a19421638a59be5a04b51b0f3c6beaef68e06a0327b5e47b62" args="" -->piaEXCLUSIVE</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="289d71610e1123a19421638a59be5a04eeea872de7ed970fa35d2c5a17faebd5"></a><!-- doxytag: member="piaSHARE" ref="289d71610e1123a19421638a59be5a04eeea872de7ed970fa35d2c5a17faebd5" args="" -->piaSHARE</em>&nbsp;</td><td>
</td></tr>
</table>
</dl>
    </td>
  </tr>
</table>
<a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf"></a><!-- doxytag: member="OPI::PIREPL" ref="a609ba1fa786f53c52e72cfe3417a5bf" args="" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">enum <a class="el" href="namespaceOPI.php#a609ba1fa786f53c52e72cfe3417a5bf">OPI::PIREPL</a>          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
<dl compact><dt><b>Enumerator: </b></dt><dd>
<table border="0" cellspacing="2" cellpadding="0">
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf4a469d4d7920735fc715784cf13170c4"></a><!-- doxytag: member="piaREPLGUID" ref="a609ba1fa786f53c52e72cfe3417a5bf4a469d4d7920735fc715784cf13170c4" args="" -->piaREPLGUID</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf77f4f252f28b8642d8ab8c2f24af1ef8"></a><!-- doxytag: member="piaREPLDIRECT" ref="a609ba1fa786f53c52e72cfe3417a5bf77f4f252f28b8642d8ab8c2f24af1ef8" args="" -->piaREPLDIRECT</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bfc4f2d3fd96fdc900a039e62b3b1f61a9"></a><!-- doxytag: member="piaREPLNONE" ref="a609ba1fa786f53c52e72cfe3417a5bfc4f2d3fd96fdc900a039e62b3b1f61a9" args="" -->piaREPLNONE</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf8da049eb7e3f4a27ee094560398bca78"></a><!-- doxytag: member="piaREPLLOCAL" ref="a609ba1fa786f53c52e72cfe3417a5bf8da049eb7e3f4a27ee094560398bca78" args="" -->piaREPLLOCAL</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf1ab7adc4be55661303a87acccbe47654"></a><!-- doxytag: member="piaREPLALL" ref="a609ba1fa786f53c52e72cfe3417a5bf1ab7adc4be55661303a87acccbe47654" args="" -->piaREPLALL</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf417ed6c1bb6de057d3231c1244a3a1e9"></a><!-- doxytag: member="piaREPLINSTANCE" ref="a609ba1fa786f53c52e72cfe3417a5bf417ed6c1bb6de057d3231c1244a3a1e9" args="" -->piaREPLINSTANCE</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf740df5595a3907753b87051fc6f7bd96"></a><!-- doxytag: member="piaREPLRELATIONSHIPS" ref="a609ba1fa786f53c52e72cfe3417a5bf740df5595a3907753b87051fc6f7bd96" args="" -->piaREPLRELATIONSHIPS</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="a609ba1fa786f53c52e72cfe3417a5bf24ea37b4fd3393889f3f19cc6eea20dd"></a><!-- doxytag: member="piaREPLNOCREATE" ref="a609ba1fa786f53c52e72cfe3417a5bf24ea37b4fd3393889f3f19cc6eea20dd" args="" -->piaREPLNOCREATE</em>&nbsp;</td><td>
</td></tr>
</table>
</dl>
    </td>
  </tr>
</table>
<a class="anchor" name="f99d2362cb8ceeee7f89f4d7484cac08"></a><!-- doxytag: member="OPI::ResourceTypes" ref="f99d2362cb8ceeee7f89f4d7484cac08" args="" --><p>
<table class="mdTable" cellpadding="2" cellspacing="0">
  <tr>
    <td class="mdRow">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td class="md" nowrap valign="top">enum <a class="el" href="namespaceOPI.php#f99d2362cb8ceeee7f89f4d7484cac08">OPI::ResourceTypes</a>          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table cellspacing="5" cellpadding="0" border="0">
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
<dl compact><dt><b>Enumerator: </b></dt><dd>
<table border="0" cellspacing="2" cellpadding="0">
<tr><td valign="top"><em><a class="anchor" name="f99d2362cb8ceeee7f89f4d7484cac0807129435e6c3683a127a7464d82f70dd"></a><!-- doxytag: member="resAUTOMATIC" ref="f99d2362cb8ceeee7f89f4d7484cac0807129435e6c3683a127a7464d82f70dd" args="" -->resAUTOMATIC</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="f99d2362cb8ceeee7f89f4d7484cac08e32e8bb68f1facd68517d9c15235753b"></a><!-- doxytag: member="resSERVER" ref="f99d2362cb8ceeee7f89f4d7484cac08e32e8bb68f1facd68517d9c15235753b" args="" -->resSERVER</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="f99d2362cb8ceeee7f89f4d7484cac082b27f61adf8e23957c089f469567e013"></a><!-- doxytag: member="resLOCAL" ref="f99d2362cb8ceeee7f89f4d7484cac082b27f61adf8e23957c089f469567e013" args="" -->resLOCAL</em>&nbsp;</td><td>
</td></tr>
<tr><td valign="top"><em><a class="anchor" name="f99d2362cb8ceeee7f89f4d7484cac08700d43b8cb141e238b6095d7a2162f5f"></a><!-- doxytag: member="resSERVERINTERN" ref="f99d2362cb8ceeee7f89f4d7484cac08700d43b8cb141e238b6095d7a2162f5f" args="" -->resSERVERINTERN</em>&nbsp;</td><td>
</td></tr>
</table>
</dl>
    </td>
  </tr>
</table>
<? include "layout/foot.inc.php";?>
