# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 


TEMPLATE = subdirs 
SUBDIRS += framework \
           linktest/testframework \
           plugins \
           applications

#           plugins \
#           linktest/testplugins \
