#!/bin/sh

echo Starting ODABAICEServer in debug mode

#make sure libopa90.so and libsos90.so (ODABA Librarys) are available
#LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/odaba/lib/:/opt/Ice-3.0.1/lib/" && export LD_LIBRARY_PATH 
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/odaba/lib/" && export LD_LIBRARY_PATH 

TRACE=/tmp/odaba && export TRACE
echo type 'run' to start the server
echo create breakpoints using 
echo break FileName:Line \(e.g: OPII.cpp:6002 \)
echo set args --Ice.Config=/etc/odaba/opiice/config
gdb bin/OPIICEServer
