#!/bin/sh

echo generating code from odaba using OSI (not tested in linux)

#make sure libopa90.so and libsos90.so (ODABA Librarys) are available
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/odaba/lib/" && export LD_LIBRARY_PATH 
/oph/odaba/bin/OSI osi/generateice.osi -I osi/ini 
