#!/bin/sh
echo calling the php script N times in a xterm to simulate concurrent
echo accesses to the interface

echo you should have ran testphp successfull before

for ((i=0;i<30;i++)) ; do ./scripts/testphpxt; done