svn update ./db4oj/src/main/java/com
svn update ./db4oj.tests/src/main/java/com
svn update ./db4oj.tests/src/main/resources/test
svn update ./db4ounit/src/main/java/db4ounit
svn update ./db4ounit/src/main/resources/META-INF
svn update ./db4ojdk1.2/src/main/java/com
svn update ./db4ounit.extensions/src/main/java/db4ounit
svn update ./db4ojdk5/src/main/java/com
svn update ./db4oj.tools/src/main/java/com
svn update ./db4ojdk5.plugins/src/main/java/com
svn update ./db4onqopt/src/main/java/com
svn update ./bloat/src/main/java/EDU
svn update ./db4onqopt.tests/src/main/java/com
svn update ./db4onqopt.testsExe/src/main/java/com
svn update ./db4ojdk1.2.tests/src/main/java/com
svn update ./db4ojdk1.2.tests/src/main/resources/db4oVersions
svn update ./db4ojdk5.tests/src/main/java/com
svn update ./db4ojdk5.tests/src/main/resources/db4oVersions
