/******************************** Interface Declaration *****************************************************/
/**
\class OPA

\brief Class and Function Numbers for Client Server Interface

\date $Date: 2006/07/24 14:29:06,87 $
\dbsource l:\opa\opa.dev - ODABA Version 9.0

 */
/*************************************************************************************/

#define   S_CACObject                  1
#define       SF_CACObject_CACObject_ci                      0
#define       SF_CACObject_CACObject_ci1                     1
#define       SF_CACObject_CACObject_ci2                     2
#define       SF_CACObject_ChangeTimeStamp_ci                3
#define       SF_CACObject_CloseObject_ci                    4
#define       SF_CACObject_DeleteExtent_ci                   5
#define       SF_CACObject_DeleteExtentRef_ci                6
#define       SF_CACObject_ExecObjCtxFunc_ci                 7
#define       SF_CACObject_ExtentExist_ci                    8
#define       SF_CACObject_GetAccess_ci                      9
#define       SF_CACObject_GetExtent_ci                      10
#define       SF_CACObject_GetModCount_ci                    11
#define       SF_CACObject_GetTALevel_ci                     12
#define       SF_CACObject_GetTimeStamp_ci                   13
#define       SF_CACObject_GetVersion_ci                     14
#define       SF_CACObject_NewVersion_ci                     15
#define       SF_CACObject_SetOverload_ci                    16
#define       SF_CACObject_SetUserDefinedIdentity_ci         17
#define       SF_CACObject_SetVersion_ci0                    18
#define       SF_CACObject_SetVersion_ci1                    19
#define       SF_CACObject_SetVersion_ci2                    20
#define       SF_CACObject_StartTA_ci                        21
#define       SF_CACObject_StopTA_ci                         22
#define       SF_CACObject_UpdateTimestamp_ci                23
#define       SF_CACObject_VersionCount_ci                   24
#define       SF_CACObject_VersionIntervall_ci               25

#define   S_CClient                    2
#define       SF_CClient_BackupDB_ci                         0
#define       SF_CClient_CacheConnection_ci                  1
#define       SF_CClient_CheckDB_ci                          2
#define       SF_CClient_DictDisplay_ci                      3
#define       SF_CClient_Exist_ci                            4
#define       SF_CClient_GetClientHandle_ci0                 5
#define       SF_CClient_GetClientHandle_ci1                 6
#define       SF_CClient_GetDBError_ci                       7
#define       SF_CClient_GetDataSource_ci                    8
#define       SF_CClient_GetHandleInfo_ci1                   9
#define       SF_CClient_GetMachineType_ci                   10
#define       SF_CClient_GetPointerSize_ci                   11
#define       SF_CClient_GetServerVariable_ci                12
#define       SF_CClient_GetServerVersion_ci                 13
#define       SF_CClient_KillClient_ci                       14
#define       SF_CClient_RestoreDB_ci                        15
#define       SF_CClient_SayHello_ci                         16
#define       SF_CClient_SendClientMessage_ci0               17
#define       SF_CClient_SetClientName_ci                    18
#define       SF_CClient_SetServerVariable_ci                19
#define       SF_CClient_SetupDataSource_ci                  20
#define       SF_CClient_StartPause_ci                       21
#define       SF_CClient_StatDisplay_ci                      22
#define       SF_CClient_StopPause_ci                        23
#define       SF_CClient_SysInfoDisplay_ci                   24

#define   S_CDBHandle                  3
#define       SF_CDBHandle_ActivateShadowBase_ci             0
#define       SF_CDBHandle_CDBHandle_ci0                     1
#define       SF_CDBHandle_ChangeRecovery_ci                 2
#define       SF_CDBHandle_CheckLicence_ci1                  3
#define       SF_CDBHandle_CheckLicence_ci2                  4
#define       SF_CDBHandle_CloseDBHandle_ci                  5
#define       SF_CDBHandle_CloseRecovery_ci                  6
#define       SF_CDBHandle_CloseWorkspace_ci                 7
#define       SF_CDBHandle_ConsolidateWorkspace_ci           8
#define       SF_CDBHandle_DeactivateShadowBase_ci           9
#define       SF_CDBHandle_DeleteWorkspace_ci                10
#define       SF_CDBHandle_DisableWorkspace_ci               11
#define       SF_CDBHandle_DiscardWorkspace_ci               12
#define       SF_CDBHandle_EnableWorkspace_ci                13
#define       SF_CDBHandle_ExecDBCtxFunc_ci                  14
#define       SF_CDBHandle_ExistWorkspace_ci                 15
#define       SF_CDBHandle_FlushClusterPool_ci               16
#define       SF_CDBHandle_GetDatabaseID_ci                  17
#define       SF_CDBHandle_GetNewTypeID_cidb                 18
#define       SF_CDBHandle_GetPath_ci                        19
#define       SF_CDBHandle_GetRecoveryFile_ci                20
#define       SF_CDBHandle_GetRecoveryNum_ci                 21
#define       SF_CDBHandle_GetRecoveryPath_ci                22
#define       SF_CDBHandle_GetRecoveryStartNumber_ci         23
#define       SF_CDBHandle_GetRecoveryType_ci                24
#define       SF_CDBHandle_GetSchemaVersion_ci               25
#define       SF_CDBHandle_GetSystemVersion_ci               26
#define       SF_CDBHandle_GetVersionString_ci               27
#define       SF_CDBHandle_GetWorkspace_ci                   28
#define       SF_CDBHandle_InitDataArea_ci                   29
#define       SF_CDBHandle_InitMainBase_ci                   30
#define       SF_CDBHandle_InitRecovery_ci                   31
#define       SF_CDBHandle_InitSubBase_ci                    32
#define       SF_CDBHandle_IsLicenced_ci                     33
#define       SF_CDBHandle_LocateWorkspace_ci                34
#define       SF_CDBHandle_OpenRecovery_ci                   35
#define       SF_CDBHandle_OpenWorkspace_ci                  36
#define       SF_CDBHandle_ResetLastSchemaVersion_ci         37
#define       SF_CDBHandle_ResetLastVersion_ci               38
#define       SF_CDBHandle_SetupTypeID_cidb                  39

#define   S_CDictionary                4
#define       SF_CDictionary_CDictionary_ci0                 0
#define       SF_CDictionary_CloseDictionary_ci              1
#define       SF_CDictionary_CreateExtentDef_ci              2
#define       SF_CDictionary_CreateStructDef_ci              3
#define       SF_CDictionary_CreateTempExtent_ci             4
#define       SF_CDictionary_GetTempName_ci                  5

#define   S_CNode                      5
#define       SF_CNode_Add_ci                                0
#define       SF_CNode_AddReference_ci0                      1
#define       SF_CNode_CanUpdateCollection_ci                2
#define       SF_CNode_Cancel_ci0                            3
#define       SF_CNode_ChangeBuffer_ci0                      4
#define       SF_CNode_ChangeMode_ci0                        5
#define       SF_CNode_CheckReadOnly_ci                      6
#define       SF_CNode_CheckWProtect_ci0                     7
#define       SF_CNode_Close_ci0                             8
#define       SF_CNode_Contains_ci                           9
#define       SF_CNode_CopyInst_ci                           10
#define       SF_CNode_CopySet_ci                            11
#define       SF_CNode_Delete_ci0                            12
#define       SF_CNode_Delete_ci1                            13
#define       SF_CNode_DeleteSet_ci                          14
#define       SF_CNode_DisableKeyCheck_ci0                   15
#define       SF_CNode_Duplicate_ci0                         16
#define       SF_CNode_EnableKeyCheck_ci0                    17
#define       SF_CNode_ExecPropCtxFunc_ci                    18
#define       SF_CNode_ExecStrCtxFunc_ci                     19
#define       SF_CNode_FirstKey_ci                           20
#define       SF_CNode_Get_ci0                               21
#define       SF_CNode_Get_ci1                               22
#define       SF_CNode_GetCollectionID_ci                    23
#define       SF_CNode_GetCount_ci                           24
#define       SF_CNode_GetGenAttrType_ci                     25
#define       SF_CNode_GetGenOrderType_ci                    26
#define       SF_CNode_GetGlobalID_ci0                       27
#define       SF_CNode_GetID_ci0                             28
#define       SF_CNode_GetID_ci1                             29
#define       SF_CNode_GetID_ByID_ci1                        30
#define       SF_CNode_GetInstModCount_ci                    31
#define       SF_CNode_GetKey_ci                             32
#define       SF_CNode_GetRefModCount_ci                     33
#define       SF_CNode_GetRelative_ci0                       34
#define       SF_CNode_GetRelativeCount_ci                   35
#define       SF_CNode_GetRelativeIndex_ci                   36
#define       SF_CNode_GetSelectedKey_ci                     37
#define       SF_CNode_Get_ByID_ci1                          38
#define       SF_CNode_Group_ci                              39
#define       SF_CNode_IsNewInstance_ci                      40
#define       SF_CNode_Locate_ci                             41
#define       SF_CNode_LocateKey_ci                          42
#define       SF_CNode_Lock_ci                               43
#define       SF_CNode_LockSet_ci                            44
#define       SF_CNode_Modify_ci                             45
#define       SF_CNode_Move_ci                               46
#define       SF_CNode_MoveDown_ci                           47
#define       SF_CNode_MoveUp_ci                             48
#define       SF_CNode_NextKey_ci                            49
#define       SF_CNode_OpenAccessPath_ci1                    50
#define       SF_CNode_OpenAccessPath_ci2                    51
#define       SF_CNode_OpenBaseNode_ci                       52
#define       SF_CNode_OpenCopyNode_ci                       53
#define       SF_CNode_OpenOperationNode_ci1                 54
#define       SF_CNode_OpenOperationNode_ci2                 55
#define       SF_CNode_OpenPathCopy_ci                       56
#define       SF_CNode_OpenSubNode_ci                        57
#define       SF_CNode_Position_ci                           58
#define       SF_CNode_ProvGenAttribute_ci                   59
#define       SF_CNode_Provide_ci0                           60
#define       SF_CNode_Provide_ci1                           61
#define       SF_CNode_Provide_ci2                           62
#define       SF_CNode_ProvideGUID_ci                        63
#define       SF_CNode_ReadBuffer_ci0                        64
#define       SF_CNode_Refresh_ci                            65
#define       SF_CNode_RegisterHandle_ci                     66
#define       SF_CNode_RemoveFromCollection_ci               67
#define       SF_CNode_Rename_ci                             68
#define       SF_CNode_Reopen_intern_ci                      69
#define       SF_CNode_RepairIndex_ci                        70
#define       SF_CNode_Reset_ci                              71
#define       SF_CNode_ResetExpression_ci                    72
#define       SF_CNode_ResetWProtect_ci                      73
#define       SF_CNode_Save_intern_ci                        74
#define       SF_CNode_SetAction_ci                          75
#define       SF_CNode_SetBaseNode_ci                        76
#define       SF_CNode_SetContextVariables_ci                77
#define       SF_CNode_SetExpression_ci                      78
#define       SF_CNode_SetGenAttribute_ci                    79
#define       SF_CNode_SetInstAction_ci                      80
#define       SF_CNode_SetOrder_ci                           81
#define       SF_CNode_SetType_ci                            82
#define       SF_CNode_SetWProtect_ci                        83
#define       SF_CNode_Unlock_ci                             84
#define       SF_CNode_UnlockSet_ci                          85
#define       SF_CNode_UnregisterHandle_ci                   86
#define       SF_CNode_Update_intern_ci                      87

#define   S_COperation                 6
#define       SF_COperation_Execute_ci                       0
#define       SF_COperation_Open_ci                          1
#define       SF_COperation_ProvExpression_ci1               2
#define       SF_COperation_ProvExpression_ci2               3
