.TH "OPI" 3 "25 Jul 2006" "OPIICE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCheckOptions\fP"
.br
.ti -1c
.RI "class \fBDBObjectHandle\fP"
.br
.ti -1c
.RI "class \fBDataSourceHandle\fP"
.br
.ti -1c
.RI "class \fBDatabaseHandle\fP"
.br
.ti -1c
.RI "class \fBODABAClient\fP"
.br
.ti -1c
.RI "class \fBOperationHandle\fP"
.br
.ti -1c
.RI "class \fBPropertyHandle\fP"
.br
.ti -1c
.RI "class \fBOPIFactory\fP"
.br
.ti -1c
.RI "class \fBSession\fP"
.br
.ti -1c
.RI "class \fBSessionFactory\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPIACC\fP { \fBpiaREAD\fP, \fBpiaWRITE\fP, \fBpiaUPDATE\fP, \fBpiaUNDEFINED\fP }"
.br
.ti -1c
.RI "enum \fBPIREPL\fP { \fBpiaREPLGUID\fP, \fBpiaREPLDIRECT\fP, \fBpiaREPLNONE\fP, \fBpiaREPLLOCAL\fP, \fBpiaREPLALL\fP, \fBpiaREPLINSTANCE\fP, \fBpiaREPLRELATIONSHIPS\fP, \fBpiaREPLNOCREATE\fP }"
.br
.ti -1c
.RI "enum \fBPIADEF\fP { \fBpiaUNKNOWN\fP, \fBpiaEXCLUSIVE\fP, \fBpiaSHARE\fP }"
.br
.ti -1c
.RI "enum \fBResourceTypes\fP { \fBresAUTOMATIC\fP, \fBresSERVER\fP, \fBresLOCAL\fP, \fBresSERVERINTERN\fP }"
.br
.ti -1c
.RI "enum \fBApplicationTypes\fP { \fBaptWINDOWS\fP, \fBaptCONSOLE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBOPI::ApplicationTypes\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIaptWINDOWS \fP\fP
.TP
\fB\fIaptCONSOLE \fP\fP

.SS "enum \fBOPI::PIACC\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIpiaREAD \fP\fP
.TP
\fB\fIpiaWRITE \fP\fP
.TP
\fB\fIpiaUPDATE \fP\fP
.TP
\fB\fIpiaUNDEFINED \fP\fP

.SS "enum \fBOPI::PIADEF\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIpiaUNKNOWN \fP\fP
.TP
\fB\fIpiaEXCLUSIVE \fP\fP
.TP
\fB\fIpiaSHARE \fP\fP

.SS "enum \fBOPI::PIREPL\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIpiaREPLGUID \fP\fP
.TP
\fB\fIpiaREPLDIRECT \fP\fP
.TP
\fB\fIpiaREPLNONE \fP\fP
.TP
\fB\fIpiaREPLLOCAL \fP\fP
.TP
\fB\fIpiaREPLALL \fP\fP
.TP
\fB\fIpiaREPLINSTANCE \fP\fP
.TP
\fB\fIpiaREPLRELATIONSHIPS \fP\fP
.TP
\fB\fIpiaREPLNOCREATE \fP\fP

.SS "enum \fBOPI::ResourceTypes\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIresAUTOMATIC \fP\fP
.TP
\fB\fIresSERVER \fP\fP
.TP
\fB\fIresLOCAL \fP\fP
.TP
\fB\fIresSERVERINTERN \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIICE from the source code.
