.TH "OPI.cpp" 3 "25 Jul 2006" "OPIICE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI.cpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBOPI\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOPI::CheckOptions\fP"
.br
.ti -1c
.RI "class \fBOPI::DBObjectHandle\fP"
.br
.ti -1c
.RI "class \fBOPI::DataSourceHandle\fP"
.br
.ti -1c
.RI "class \fBOPI::DBObjectHandle\fP"
.br
.ti -1c
.RI "class \fBOPI::DatabaseHandle\fP"
.br
.ti -1c
.RI "class \fBOPI::ODABAClient\fP"
.br
.ti -1c
.RI "class \fBOPI::OperationHandle\fP"
.br
.ti -1c
.RI "class \fBOPI::PropertyHandle\fP"
.br
.ti -1c
.RI "class \fBOPI::OPIFactory\fP"
.br
.ti -1c
.RI "class \fBOPI::Session\fP"
.br
.ti -1c
.RI "class \fBOPI::SessionFactory\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBOPI::PIACC\fP { \fBOPI::piaREAD\fP, \fBOPI::piaWRITE\fP, \fBOPI::piaUPDATE\fP, \fBOPI::piaUNDEFINED\fP }"
.br
.ti -1c
.RI "enum \fBOPI::PIREPL\fP { \fBOPI::piaREPLGUID\fP, \fBOPI::piaREPLDIRECT\fP, \fBOPI::piaREPLNONE\fP, \fBOPI::piaREPLLOCAL\fP, \fBOPI::piaREPLALL\fP, \fBOPI::piaREPLINSTANCE\fP, \fBOPI::piaREPLRELATIONSHIPS\fP, \fBOPI::piaREPLNOCREATE\fP }"
.br
.ti -1c
.RI "enum \fBOPI::PIADEF\fP { \fBOPI::piaUNKNOWN\fP, \fBOPI::piaEXCLUSIVE\fP, \fBOPI::piaSHARE\fP }"
.br
.ti -1c
.RI "enum \fBOPI::ResourceTypes\fP { \fBOPI::resAUTOMATIC\fP, \fBOPI::resSERVER\fP, \fBOPI::resLOCAL\fP, \fBOPI::resSERVERINTERN\fP }"
.br
.ti -1c
.RI "enum \fBOPI::ApplicationTypes\fP { \fBOPI::aptWINDOWS\fP, \fBOPI::aptCONSOLE\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIICE from the source code.
