.TH "OPI::OPIFactory" 3 "25 Jul 2006" "OPIICE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI::OPIFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBDestroy\fP ()"
.br
.ti -1c
.RI "\fBCheckOptions\fP * \fBGetCheckOptions\fP ()"
.br
.ti -1c
.RI "\fBDBObjectHandle\fP * \fBGetDBObjectHandle\fP ()"
.br
.ti -1c
.RI "\fBDataSourceHandle\fP * \fBGetDataSourceHandle\fP ()"
.br
.ti -1c
.RI "\fBDatabaseHandle\fP * \fBGetDatabaseHandle\fP ()"
.br
.ti -1c
.RI "DictionaryHandle * \fBGetDictionaryHandle\fP ()"
.br
.ti -1c
.RI "\fBODABAClient\fP * \fBGetODABAClient\fP ()"
.br
.ti -1c
.RI "\fBOperationHandle\fP * \fBGetOperationHandle\fP ()"
.br
.ti -1c
.RI "\fBPropertyHandle\fP * \fBGetPropertyHandle\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void OPI::OPIFactory::Destroy ()\fC [private]\fP"
.PP
.SS "\fBCheckOptions\fP* OPI::OPIFactory::GetCheckOptions ()\fC [private]\fP"
.PP
.SS "\fBDatabaseHandle\fP* OPI::OPIFactory::GetDatabaseHandle ()\fC [private]\fP"
.PP
.SS "\fBDataSourceHandle\fP* OPI::OPIFactory::GetDataSourceHandle ()\fC [private]\fP"
.PP
.SS "\fBDBObjectHandle\fP* OPI::OPIFactory::GetDBObjectHandle ()\fC [private]\fP"
.PP
.SS "DictionaryHandle* OPI::OPIFactory::GetDictionaryHandle ()\fC [private]\fP"
.PP
.SS "\fBODABAClient\fP* OPI::OPIFactory::GetODABAClient ()\fC [private]\fP"
.PP
.SS "\fBOperationHandle\fP* OPI::OPIFactory::GetOperationHandle ()\fC [private]\fP"
.PP
.SS "\fBPropertyHandle\fP* OPI::OPIFactory::GetPropertyHandle ()\fC [private]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OPIICE from the source code.
