.TH "OPI::CheckOptions" 3 "25 Jul 2006" "OPIICE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI::CheckOptions \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool * \fBInitialize\fP (string parmstring)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool* OPI::CheckOptions::Initialize (string parmstring)\fC [private]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OPIICE from the source code.
