.TH "OPI::OperationHandle" 3 "25 Jul 2006" "OPIICE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI::OperationHandle \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckExpression\fP (DictionaryHandle *dictptr, string expression, \fBDBObjectHandle\fP *obhandle, string clsnames)"
.br
.ti -1c
.RI "bool \fBCheckExpressionInClass\fP (DictionaryHandle *dictptr, \fBDBObjectHandle\fP *resobj, string clsnames, string exprnames, string impnames)"
.br
.ti -1c
.RI "bool \fBExecute\fP ()"
.br
.ti -1c
.RI "\fBPropertyHandle\fP * \fBGetResult\fP ()"
.br
.ti -1c
.RI "int \fBGetSize\fP ()"
.br
.ti -1c
.RI "bool \fBIsValid\fP ()"
.br
.ti -1c
.RI "bool \fBOpen\fP (\fBPropertyHandle\fP *prophdlref)"
.br
.ti -1c
.RI "bool \fBProvideExpression\fP (DictionaryHandle *pdictionary, \fBDBObjectHandle\fP *resobj, \fBDBObjectHandle\fP *obhandle, string expression)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool OPI::OperationHandle::CheckExpression (DictionaryHandle * dictptr, string expression, \fBDBObjectHandle\fP * obhandle, string clsnames)\fC [private]\fP"
.PP
.SS "bool OPI::OperationHandle::CheckExpressionInClass (DictionaryHandle * dictptr, \fBDBObjectHandle\fP * resobj, string clsnames, string exprnames, string impnames)\fC [private]\fP"
.PP
.SS "bool OPI::OperationHandle::Execute ()\fC [private]\fP"
.PP
.SS "\fBPropertyHandle\fP* OPI::OperationHandle::GetResult ()\fC [private]\fP"
.PP
.SS "int OPI::OperationHandle::GetSize ()\fC [private]\fP"
.PP
.SS "bool OPI::OperationHandle::IsValid ()\fC [private]\fP"
.PP
.SS "bool OPI::OperationHandle::Open (\fBPropertyHandle\fP * prophdlref)\fC [private]\fP"
.PP
.SS "bool OPI::OperationHandle::ProvideExpression (DictionaryHandle * pdictionary, \fBDBObjectHandle\fP * resobj, \fBDBObjectHandle\fP * obhandle, string expression)\fC [private]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OPIICE from the source code.
