.TH "OPI::Session" 3 "25 Jul 2006" "OPIICE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI::Session \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBOPIFactory\fP * \fBCreateSession\fP ()"
.br
.ti -1c
.RI "void \fBDestroy\fP ()"
.br
.ti -1c
.RI "void \fBTimeOut\fP (int seconds)"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBOPIFactory\fP* OPI::Session::CreateSession ()\fC [private]\fP"
.PP
.SS "void OPI::Session::Destroy ()\fC [private]\fP"
.PP
.SS "string OPI::Session::getName ()\fC [private]\fP"
.PP
.SS "void OPI::Session::TimeOut (int seconds)\fC [private]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OPIICE from the source code.
