.TH "OPI::SessionFactory" 3 "25 Jul 2006" "OPIICE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPI::SessionFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBSession\fP * \fBCreateProxy\fP (string name)"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBSession\fP* OPI::SessionFactory::CreateProxy (string name)\fC [private]\fP"
.PP
.SS "void OPI::SessionFactory::shutdown ()\fC [private]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OPIICE from the source code.
