// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package de.tmobile.cabu.entities;

/**
 * @see de.openaqua.dev.alma.Contract
 */
public class ContractImpl
    extends de.tmobile.cabu.entities.Contract
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3294393485767974808L;

}