// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package de.tmobile.cabu.entities;


/**
 * 
 */
public abstract class Contract
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3294393485767974808L;

    private java.lang.String msisdn;

    /**
     * 
     */
    public java.lang.String getMsisdn()
    {
        return this.msisdn;
    }

    public void setMsisdn(java.lang.String msisdn)
    {
        this.msisdn = msisdn;
    }

    private java.lang.String contractId;

    /**
     * 
     */
    public java.lang.String getContractId()
    {
        return this.contractId;
    }

    public void setContractId(java.lang.String contractId)
    {
        this.contractId = contractId;
    }

    private int validFrom;

    /**
     * 
     */
    public int getValidFrom()
    {
        return this.validFrom;
    }

    public void setValidFrom(int validFrom)
    {
        this.validFrom = validFrom;
    }

    private int validTo;

    /**
     * 
     */
    public int getValidTo()
    {
        return this.validTo;
    }

    public void setValidTo(int validTo)
    {
        this.validTo = validTo;
    }

    private java.lang.Long id;

    /**
     * 
     */
    public java.lang.Long getId()
    {
        return this.id;
    }

    public void setId(java.lang.Long id)
    {
        this.id = id;
    }

    /**
     * Returns <code>true</code> if the argument is an Contract instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Contract))
        {
            return false;
        }
        final Contract that = (Contract)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (id == null ? 0 : id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link de.openaqua.dev.alma.Contract}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link de.openaqua.dev.alma.Contract}.
         */
        public static de.tmobile.cabu.entities.Contract newInstance()
        {
            return new de.tmobile.cabu.entities.ContractImpl();
        }


        /**
         * Constructs a new instance of {@link de.openaqua.dev.alma.Contract}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static de.tmobile.cabu.entities.Contract newInstance(java.lang.String msisdn, java.lang.String contractId, int validFrom, int validTo)
        {
            final de.tmobile.cabu.entities.Contract entity = new de.tmobile.cabu.entities.ContractImpl();
            entity.setMsisdn(msisdn);
            entity.setContractId(contractId);
            entity.setValidFrom(validFrom);
            entity.setValidTo(validTo);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}