package connector;


/**
* connector/GetUidOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test.idl
* Wednesday, December 27, 2006 2:18:08 PM CET
*/

public interface GetUidOperations 
{
  String getUid ();
} // interface GetUidOperations
