package connector;


/**
* connector/GetUidHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test.idl
* Wednesday, December 27, 2006 2:18:08 PM CET
*/

abstract public class GetUidHelper
{
  private static String  _id = "IDL:connector/GetUid:1.0";

  public static void insert (org.omg.CORBA.Any a, connector.GetUid that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static connector.GetUid extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (connector.GetUidHelper.id (), "GetUid");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static connector.GetUid read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GetUidStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, connector.GetUid value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static connector.GetUid narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof connector.GetUid)
      return (connector.GetUid)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      connector._GetUidStub stub = new connector._GetUidStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
