package connector;

/**
* connector/GetUidHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test.idl
* Wednesday, December 27, 2006 2:18:08 PM CET
*/

public final class GetUidHolder implements org.omg.CORBA.portable.Streamable
{
  public connector.GetUid value = null;

  public GetUidHolder ()
  {
  }

  public GetUidHolder (connector.GetUid initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = connector.GetUidHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    connector.GetUidHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return connector.GetUidHelper.type ();
  }

}
